"""Configuración de entidades del repositorio: metadatos de tablas y dominios."""

ENTITY_CONFIG = {
    "regional": {
        "table": "regional",
        "label": "Regional",
        "parent_key": None,
        "fields": ["nombre"],
        "required": ["nombre"],
        "context_key": "regional_id",
        "select_aliases": {},
        "form_to_db": {},
    },
    "centro": {
        "table": "centro",
        "label": "Centro de formación",
        "parent_key": "regional_id",
        "fields": ["regional_id", "nombre"],
        "required": ["regional_id", "nombre"],
        "context_key": "centro_id",
        "select_aliases": {},
        "form_to_db": {},
    },
    "coordinacion": {
        "table": "coordinacion",
        "label": "Coordinación",
        "parent_key": "centro_id",
        "fields": ["centro_id", "nombre"],
        "required": ["centro_id", "nombre"],
        "context_key": "coordinacion_id",
        "select_aliases": {},
        "form_to_db": {},
    },
    "sede": {
        "table": "sede",
        "label": "Sede",
        "parent_key": "centro_id",
        "fields": ["centro_id", "nombre"],
        "required": ["centro_id", "nombre"],
        "context_key": "sede_id",
        "select_aliases": {},
        "form_to_db": {},
    },
    "instructor": {
        "table": "instructor",
        "label": "Instructor",
        "parent_key": "centro_id",
        "fields": ["centro_id", "area_id", "documento", "nombres", "apellidos", "correo"],
        "required": ["centro_id", "documento", "nombres", "apellidos"],
        "context_key": "centro_id",
        "select_aliases": {
            "correo": "email",
            "usuario_id": "user_id",
        },
        "form_to_db": {"email": "correo"},
    },
    "aprendiz": {
        "table": "aprendiz",
        "label": "Aprendiz",
        "parent_key": "regional_id",
        "fields": ["regional_id", "documento", "nombres", "apellidos", "correo", "ficha"],
        "required": ["regional_id", "documento", "nombres", "apellidos"],
        "context_key": "regional_id",
        "select_aliases": {"correo": "email", "usuario_id": "user_id"},
        "form_to_db": {},
    },
    "ambiente": {
        "table": "ambiente",
        "label": "Ambiente",
        "parent_key": "sede_id",
        "fields": ["sede_id", "nombre", "capacidad"],
        "required": ["sede_id", "nombre"],
        "context_key": "sede_id",
        "select_aliases": {},
        "form_to_db": {},
    },
    "red": {
        "table": "red_conocimiento",
        "label": "Red de conocimiento",
        "parent_key": None,
        "fields": ["nombre"],
        "required": ["nombre"],
        "context_key": "red_id",
        "select_aliases": {},
        "form_to_db": {},
    },
    "area": {
        "table": "area",
        "label": "Area",
        "parent_key": "red_id",
        "fields": ["red_conocimiento_id", "nombre"],
        "required": ["red_conocimiento_id", "nombre"],
        "context_key": "area_id",
        "select_aliases": {"red_conocimiento_id": "red_id"},
        "form_to_db": {"red_id": "red_conocimiento_id"},
    },
    "nivel": {
        "table": "nivel_formacion",
        "label": "Nivel de formación",
        "parent_key": None,
        "fields": ["nombre"],
        "required": ["nombre"],
        "context_key": "nivel_id",
        "select_aliases": {},
        "form_to_db": {},
    },
    "programa": {
        "table": "programa_formacion",
        "label": "Programa de formación",
        "parent_key": "area_id",
        "fields": ["area_id", "nivel_formacion_id", "nombre"],
        "required": ["area_id", "nivel_formacion_id", "nombre"],
        "context_key": "programa_id",
        "select_aliases": {"nivel_formacion_id": "nivel_id"},
        "form_to_db": {"nivel_id": "nivel_formacion_id"},
    },
    "ficha": {
        "table": "ficha_formacion",
        "label": "Ficha de formación",
        "parent_key": "programa_id",
        "fields": [
            "numero",
            "programa_formacion_id",
            "proyecto_formativo_id",
            "coordinacion_id",
            "instructor_id",
        ],
        "required": [
            "numero",
            "programa_formacion_id",
            "proyecto_formativo_id",
            "coordinacion_id",
        ],
        "context_key": "programa_id",
        "select_aliases": {"programa_formacion_id": "programa_id"},
        "form_to_db": {"programa_id": "programa_formacion_id"},
    },
    "proyecto_formativo": {
        "table": "proyecto_formativo",
        "label": "Proyecto formativo",
        "parent_key": None,
        "fields": ["codigo", "nombre"],
        "required": ["codigo", "nombre"],
        "context_key": "proyecto_formativo_id",
        "select_aliases": {},
        "form_to_db": {},
    },
    "fase_proyecto": {
        "table": "fase_proyecto",
        "label": "Fase del proyecto",
        "parent_key": "proyecto_formativo_id",
        "fields": ["proyecto_formativo_id", "nombre"],
        "required": ["proyecto_formativo_id", "nombre"],
        "context_key": "fase_id",
        "select_aliases": {},
        "form_to_db": {},
    },
    "actividad_proyecto": {
        "table": "actividad_proyecto",
        "label": "Actividad del proyecto",
        "parent_key": "fase_id",
        "fields": ["fase_proyecto_id", "nombre"],
        "required": ["fase_proyecto_id", "nombre"],
        "context_key": "fase_id",
        "select_aliases": {"fase_proyecto_id": "fase_id"},
        "form_to_db": {"fase_id": "fase_proyecto_id"},
    },
    "actividad_aprendizaje": {
        "table": "actividad_aprendizaje",
        "label": "Actividad de aprendizaje",
        "parent_key": "actividad_proyecto_id",
        "fields": ["actividad_proyecto_id", "nombre"],
        "required": ["actividad_proyecto_id", "nombre"],
        "context_key": "actividad_proyecto_id",
        "select_aliases": {},
        "form_to_db": {},
    },
    "administrativo_persona": {
        "table": "personal_administrativo",
        "label": "Personal administrativo",
        "parent_key": "centro_id",
        "fields": ["centro_id", "documento", "nombres", "apellidos", "correo", "cargo"],
        "required": ["centro_id", "documento", "nombres", "apellidos", "cargo"],
        "context_key": "centro_id",
        "select_aliases": {"correo": "email", "usuario_id": "user_id"},
        "form_to_db": {},
    },
}

STRUCTURE_ENTITIES = {"regional", "centro", "coordinacion", "sede", "ambiente"}
PEOPLE_ENTITIES = {"instructor", "aprendiz", "administrativo_persona"}
ACADEMIC_ENTITIES = {
    "red", "area", "nivel", "programa", "ficha",
    "proyecto_formativo", "fase_proyecto", "actividad_proyecto", "actividad_aprendizaje",
}

PERSON_USER_CONFIG = {
    "instructor": {
        "role": "Instructor",
        "email_prefix": "instructor",
        "table": "instructor",
        "email_column": "correo",
        "user_column": "usuario_id",
    },
    "aprendiz": {
        "role": "Aprendiz",
        "email_prefix": "aprendiz",
        "table": "aprendiz",
        "email_column": "correo",
        "user_column": "usuario_id",
    },
    "administrativo_persona": {
        "role": "Administrativo",
        "email_prefix": "administrativo",
        "table": "personal_administrativo",
        "email_column": "correo",
        "user_column": "usuario_id",
    },
}
