-- ============================================================
-- Project    : bariLMS — Learning Management System (SENA)
-- File       : database/bari_lms_postgresql.sql
-- Description: Canonical PostgreSQL schema for bariLMS.
--              Supersedes database/setup_aprendiz.sql (legacy).
--
-- PostgreSQL : Requires PostgreSQL 15+
--
-- How to apply:
--   psql -U <user> -d <dbname> -f bari_lms_postgresql.sql
--   (safe to re-run; all statements use IF NOT EXISTS / ON CONFLICT)
--
-- UUID       : Generated by the application layer as UUID v7.
--              No DEFAULT on id columns — the app always provides them.
--
-- actualizado_en: NULL until the first UPDATE. Set explicitly by the
--              application in every UPDATE statement.
--
-- Tables (in dependency order):
--   Institutional structure:
--     usuario, regional, centro, coordinacion, sede, ambiente
--
--   Academic knowledge:
--     red_conocimiento, area, nivel_formacion
--
--   People:
--     instructor, aprendiz, personal_administrativo
--
--   Academic content chain:
--     proyecto_formativo, fase_proyecto, actividad_proyecto,
--     actividad_aprendizaje, guia_aprendizaje, evidencia_aprendizaje,
--     entrega_evidencia, seccion_actividad, sub_seccion_actividad,
--     guia_actividad_proyecto
--
--   Programs & fichas:
--     programa_formacion, ficha_formacion,
--     ficha_instructor_competencia, asistencia_aprendiz
--
--   Learner-facing extras:
--     fase, notificacion
-- ============================================================

BEGIN;

-- ============================================================
-- INSTITUTIONAL STRUCTURE
-- ============================================================

-- Usuarios del sistema. Todos los perfiles (admin, instructor, aprendiz,
-- administrativo) tienen una fila aquí para autenticación.
-- El perfil al que pertenece un usuario se almacena en usuario_perfil (pivote).
-- Un usuario puede tener varios perfiles simultáneamente.
-- creado_por es NULL para los usuarios seed y para el primer administrador.
CREATE TABLE IF NOT EXISTS usuario (
    id              UUID        PRIMARY KEY,
    creado_por      UUID        REFERENCES usuario(id) ON DELETE SET NULL,
    correo          TEXT        UNIQUE NOT NULL,
    contrasena_hash TEXT        NOT NULL,
    nombre          TEXT        NOT NULL,
    activo          BOOLEAN     NOT NULL DEFAULT TRUE,
    creado_en       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en  TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_usuario_correo ON usuario (lower(correo));


-- Perfiles del sistema. Define las categorías de acceso de alto nivel
-- (Administrador, Administrativo, Instructor, Aprendiz).
-- Un usuario puede pertenecer a varios perfiles vía usuario_perfil.
CREATE TABLE IF NOT EXISTS perfil (
    id             UUID        PRIMARY KEY,
    nombre         TEXT        NOT NULL UNIQUE,
    descripcion    TEXT,
    creado_en      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ,
    creado_por     UUID        REFERENCES usuario(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_perfil_creado_por ON perfil (creado_por);


-- Roles específicos dentro de un perfil. Permiten granularidad adicional
-- dentro de una misma categoría de perfil.
-- Nota: 'role' es palabra reservada en PostgreSQL; se usa 'rol'.
CREATE TABLE IF NOT EXISTS rol (
    id             UUID        PRIMARY KEY,
    perfil_id      UUID        NOT NULL REFERENCES perfil(id) ON DELETE CASCADE,
    nombre         TEXT        NOT NULL,
    descripcion    TEXT,
    creado_en      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ,
    creado_por     UUID        REFERENCES usuario(id) ON DELETE SET NULL,
    UNIQUE (perfil_id, nombre)
);

CREATE INDEX IF NOT EXISTS idx_rol_perfil_id   ON rol (perfil_id);
CREATE INDEX IF NOT EXISTS idx_rol_creado_por  ON rol (creado_por);


-- Permisos granulares del sistema.
-- codigo: identificador técnico con convención recurso.accion (ej: fichas.ver).
-- nombre: etiqueta legible para mostrar en la UI (ej: 'Ver fichas').
-- descripcion: explicación detallada de lo que habilita el permiso.
CREATE TABLE IF NOT EXISTS permiso (
    id             UUID        PRIMARY KEY,
    codigo         TEXT        NOT NULL UNIQUE,
    nombre         TEXT        NOT NULL,
    descripcion    TEXT,
    creado_en      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ,
    creado_por     UUID        REFERENCES usuario(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_permiso_codigo     ON permiso (codigo);
CREATE INDEX IF NOT EXISTS idx_permiso_creado_por ON permiso (creado_por);


-- Permisos asignados a un rol específico (nivel granular).
-- Al eliminar el rol o el permiso se elimina la asignación (CASCADE).
CREATE TABLE IF NOT EXISTS rol_permiso (
    id             UUID        PRIMARY KEY,
    rol_id         UUID        NOT NULL REFERENCES rol(id) ON DELETE CASCADE,
    permiso_id     UUID        NOT NULL REFERENCES permiso(id) ON DELETE CASCADE,
    creado_en      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ,
    creado_por     UUID        REFERENCES usuario(id) ON DELETE SET NULL,
    UNIQUE (rol_id, permiso_id)
);

CREATE INDEX IF NOT EXISTS idx_rol_permiso_rol_id     ON rol_permiso (rol_id);
CREATE INDEX IF NOT EXISTS idx_rol_permiso_permiso_id ON rol_permiso (permiso_id);


-- Perfiles asignados a un usuario. Un usuario puede tener varios perfiles.
-- Al eliminar el usuario o el perfil se elimina la asignación (CASCADE).
CREATE TABLE IF NOT EXISTS usuario_perfil (
    id             UUID        PRIMARY KEY,
    usuario_id     UUID        NOT NULL REFERENCES usuario(id) ON DELETE CASCADE,
    perfil_id      UUID        NOT NULL REFERENCES perfil(id) ON DELETE CASCADE,
    creado_en      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ,
    creado_por     UUID        REFERENCES usuario(id) ON DELETE SET NULL,
    UNIQUE (usuario_id, perfil_id)
);

CREATE INDEX IF NOT EXISTS idx_usuario_perfil_usuario_id ON usuario_perfil (usuario_id);
CREATE INDEX IF NOT EXISTS idx_usuario_perfil_perfil_id  ON usuario_perfil (perfil_id);


-- Roles específicos asignados a un usuario.
-- Al eliminar el usuario o el rol se elimina la asignación (CASCADE).
CREATE TABLE IF NOT EXISTS usuario_rol (
    id             UUID        PRIMARY KEY,
    usuario_id     UUID        NOT NULL REFERENCES usuario(id) ON DELETE CASCADE,
    rol_id         UUID        NOT NULL REFERENCES rol(id) ON DELETE CASCADE,
    creado_en      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ,
    creado_por     UUID        REFERENCES usuario(id) ON DELETE SET NULL,
    UNIQUE (usuario_id, rol_id)
);

CREATE INDEX IF NOT EXISTS idx_usuario_rol_usuario_id ON usuario_rol (usuario_id);
CREATE INDEX IF NOT EXISTS idx_usuario_rol_rol_id     ON usuario_rol (rol_id);


-- Regionales del SENA. Nivel más alto de la estructura institucional.
CREATE TABLE IF NOT EXISTS regional (
    id             UUID        PRIMARY KEY,
    nombre         TEXT        NOT NULL UNIQUE,
    creado_en      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ
);


-- Centros de formación. Pertenecen a una regional.
-- No se puede eliminar una regional que tenga centros (RESTRICT).
CREATE TABLE IF NOT EXISTS centro (
    id             UUID        PRIMARY KEY,
    regional_id    UUID        NOT NULL REFERENCES regional(id) ON DELETE RESTRICT,
    nombre         TEXT        NOT NULL,
    creado_en      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_centro_regional_id ON centro (regional_id);


-- Coordinaciones académicas dentro de un centro.
-- No se puede eliminar un centro que tenga coordinaciones (RESTRICT).
CREATE TABLE IF NOT EXISTS coordinacion (
    id             UUID        PRIMARY KEY,
    centro_id      UUID        NOT NULL REFERENCES centro(id) ON DELETE RESTRICT,
    nombre         TEXT        NOT NULL,
    creado_en      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_coordinacion_centro_id ON coordinacion (centro_id);


-- Sedes físicas dentro de un centro.
-- No se puede eliminar un centro que tenga sedes (RESTRICT).
CREATE TABLE IF NOT EXISTS sede (
    id             UUID        PRIMARY KEY,
    centro_id      UUID        NOT NULL REFERENCES centro(id) ON DELETE RESTRICT,
    nombre         TEXT        NOT NULL,
    creado_en      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_sede_centro_id ON sede (centro_id);


-- Ambientes o aulas dentro de una sede.
-- No se puede eliminar una sede que tenga ambientes (RESTRICT).
CREATE TABLE IF NOT EXISTS ambiente (
    id             UUID        PRIMARY KEY,
    sede_id        UUID        NOT NULL REFERENCES sede(id) ON DELETE RESTRICT,
    nombre         TEXT        NOT NULL,
    capacidad      INTEGER,
    creado_en      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_ambiente_sede_id ON ambiente (sede_id);

-- ============================================================
-- ACADEMIC KNOWLEDGE STRUCTURE
-- ============================================================

-- Redes de conocimiento del SENA (ej: Tecnología, Agroindustria).
CREATE TABLE IF NOT EXISTS red_conocimiento (
    id             UUID        PRIMARY KEY,
    nombre         TEXT        NOT NULL UNIQUE,
    creado_en      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ
);


-- Áreas de desempeño dentro de una red de conocimiento.
-- No se puede eliminar una red que tenga áreas (RESTRICT).
CREATE TABLE IF NOT EXISTS area (
    id                   UUID        PRIMARY KEY,
    red_conocimiento_id  UUID        NOT NULL REFERENCES red_conocimiento(id) ON DELETE RESTRICT,
    nombre               TEXT        NOT NULL,
    creado_en            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en       TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_area_red_conocimiento_id ON area (red_conocimiento_id);


-- Niveles de formación (Técnico, Tecnólogo, Operario, etc.).
CREATE TABLE IF NOT EXISTS nivel_formacion (
    id             UUID        PRIMARY KEY,
    nombre         TEXT        NOT NULL UNIQUE,
    creado_en      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ
);

-- ============================================================
-- PEOPLE
-- ============================================================

-- Instructores vinculados a un centro y opcionalmente a un área.
-- No se puede eliminar un centro o área con instructores activos (RESTRICT).
-- Si el usuario asociado es eliminado, se desvincula (SET NULL).
CREATE TABLE IF NOT EXISTS instructor (
    id             UUID        PRIMARY KEY,
    centro_id      UUID        NOT NULL REFERENCES centro(id) ON DELETE RESTRICT,
    area_id        UUID        REFERENCES area(id) ON DELETE SET NULL,
    usuario_id     UUID        REFERENCES usuario(id) ON DELETE SET NULL,
    documento      TEXT        NOT NULL,
    nombres        TEXT        NOT NULL,
    apellidos      TEXT        NOT NULL,
    correo         TEXT,
    genero         TEXT        NOT NULL DEFAULT 'M',
    creado_en      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_instructor_centro_id  ON instructor (centro_id);
CREATE INDEX IF NOT EXISTS idx_instructor_area_id    ON instructor (area_id);
CREATE INDEX IF NOT EXISTS idx_instructor_usuario_id ON instructor (usuario_id);


-- Aprendices vinculados a una regional.
-- No se puede eliminar una regional con aprendices (RESTRICT).
-- Si el usuario asociado es eliminado, se desvincula (SET NULL).
CREATE TABLE IF NOT EXISTS aprendiz (
    id             UUID        PRIMARY KEY,
    regional_id    UUID        NOT NULL REFERENCES regional(id) ON DELETE RESTRICT,
    usuario_id     UUID        REFERENCES usuario(id) ON DELETE SET NULL,
    documento      TEXT        NOT NULL,
    nombres        TEXT        NOT NULL,
    apellidos      TEXT        NOT NULL,
    correo         TEXT,
    ficha          TEXT,
    creado_en      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_aprendiz_regional_id ON aprendiz (regional_id);
CREATE INDEX IF NOT EXISTS idx_aprendiz_usuario_id  ON aprendiz (usuario_id);


-- Personal administrativo vinculado a un centro.
-- No se puede eliminar un centro con personal administrativo (RESTRICT).
CREATE TABLE IF NOT EXISTS personal_administrativo (
    id             UUID        PRIMARY KEY,
    centro_id      UUID        NOT NULL REFERENCES centro(id) ON DELETE RESTRICT,
    usuario_id     UUID        REFERENCES usuario(id) ON DELETE SET NULL,
    documento      TEXT        NOT NULL,
    nombres        TEXT        NOT NULL,
    apellidos      TEXT        NOT NULL,
    correo         TEXT,
    cargo          TEXT        NOT NULL,
    creado_en      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_personal_administrativo_centro_id  ON personal_administrativo (centro_id);
CREATE INDEX IF NOT EXISTS idx_personal_administrativo_usuario_id ON personal_administrativo (usuario_id);

-- ============================================================
-- ACADEMIC CONTENT CHAIN
-- ============================================================

-- Proyecto formativo: documento guía del proceso de formación.
CREATE TABLE IF NOT EXISTS proyecto_formativo (
    id             UUID        PRIMARY KEY,
    codigo         TEXT        NOT NULL UNIQUE,
    nombre         TEXT        NOT NULL,
    creado_en      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ
);


-- Fases del proyecto formativo (ej: Análisis, Planeación, Ejecución).
-- Al eliminar el proyecto se eliminan sus fases (CASCADE).
CREATE TABLE IF NOT EXISTS fase_proyecto (
    id                    UUID        PRIMARY KEY,
    proyecto_formativo_id UUID        NOT NULL REFERENCES proyecto_formativo(id) ON DELETE CASCADE,
    nombre                TEXT        NOT NULL,
    creado_en             TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en        TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_fase_proyecto_proyecto_formativo_id ON fase_proyecto (proyecto_formativo_id);


-- Actividades del proyecto agrupadas por fase.
-- Al eliminar la fase se eliminan sus actividades (CASCADE).
CREATE TABLE IF NOT EXISTS actividad_proyecto (
    id               UUID        PRIMARY KEY,
    fase_proyecto_id UUID        NOT NULL REFERENCES fase_proyecto(id) ON DELETE CASCADE,
    nombre           TEXT        NOT NULL,
    creado_en        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en   TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_actividad_proyecto_fase_proyecto_id ON actividad_proyecto (fase_proyecto_id);


-- Actividades de aprendizaje dentro de una actividad de proyecto.
-- Al eliminar la actividad de proyecto se eliminan las de aprendizaje (CASCADE).
CREATE TABLE IF NOT EXISTS actividad_aprendizaje (
    id                    UUID        PRIMARY KEY,
    actividad_proyecto_id UUID        NOT NULL REFERENCES actividad_proyecto(id) ON DELETE CASCADE,
    nombre                TEXT        NOT NULL,
    descripcion           TEXT,
    fecha_inicio          DATE,
    fecha_fin             DATE,
    orden                 INTEGER     NOT NULL DEFAULT 0,
    creado_en             TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en        TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_actividad_aprendizaje_actividad_proyecto_id ON actividad_aprendizaje (actividad_proyecto_id);


-- Guía de aprendizaje adjunta a una actividad (1:1).
CREATE TABLE IF NOT EXISTS guia_aprendizaje (
    id                       UUID        PRIMARY KEY,
    actividad_aprendizaje_id UUID        NOT NULL UNIQUE REFERENCES actividad_aprendizaje(id) ON DELETE CASCADE,
    url                      TEXT        NOT NULL,
    subido_en                TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    creado_en                TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en           TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_guia_aprendizaje_actividad_aprendizaje_id ON guia_aprendizaje (actividad_aprendizaje_id);


-- Evidencia de aprendizaje asociada a una actividad (1:1).
CREATE TABLE IF NOT EXISTS evidencia_aprendizaje (
    id                       UUID        PRIMARY KEY,
    actividad_aprendizaje_id UUID        NOT NULL UNIQUE REFERENCES actividad_aprendizaje(id) ON DELETE CASCADE,
    descripcion              TEXT,
    creado_en                TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en           TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_evidencia_aprendizaje_actividad_aprendizaje_id ON evidencia_aprendizaje (actividad_aprendizaje_id);


-- Entrega de evidencia por parte de un aprendiz, con calificación del instructor.
-- Al eliminar la evidencia se eliminan sus entregas (CASCADE).
-- No se puede eliminar un usuario que tenga entregas (RESTRICT).
CREATE TABLE IF NOT EXISTS entrega_evidencia (
    id                       UUID        PRIMARY KEY,
    evidencia_aprendizaje_id UUID        NOT NULL REFERENCES evidencia_aprendizaje(id) ON DELETE CASCADE,
    usuario_id               UUID        NOT NULL REFERENCES usuario(id) ON DELETE RESTRICT,
    url                      TEXT,
    calificacion             NUMERIC(5,2),
    observaciones            TEXT,
    retroalimentacion        TEXT,
    aprueba                  BOOLEAN,
    calificado_en            TIMESTAMPTZ,
    entregado_en             TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    creado_en                TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en           TIMESTAMPTZ,
    UNIQUE (evidencia_aprendizaje_id, usuario_id)
);

CREATE INDEX IF NOT EXISTS idx_entrega_evidencia_evidencia_aprendizaje_id ON entrega_evidencia (evidencia_aprendizaje_id);
CREATE INDEX IF NOT EXISTS idx_entrega_evidencia_usuario_id               ON entrega_evidencia (usuario_id);


-- Secciones dentro de una actividad de aprendizaje.
CREATE TABLE IF NOT EXISTS seccion_actividad (
    id                       UUID        PRIMARY KEY,
    actividad_aprendizaje_id UUID        NOT NULL REFERENCES actividad_aprendizaje(id) ON DELETE CASCADE,
    nombre                   TEXT        NOT NULL,
    descripcion              TEXT,
    archivo_url              TEXT,
    archivo_tipo             TEXT,
    fecha_inicio             DATE,
    fecha_fin                DATE,
    orden                    INTEGER     NOT NULL DEFAULT 0,
    creado_en                TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en           TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_seccion_actividad_actividad_aprendizaje_id ON seccion_actividad (actividad_aprendizaje_id);


-- Subsecciones dentro de una sección de actividad.
CREATE TABLE IF NOT EXISTS sub_seccion_actividad (
    id             UUID        PRIMARY KEY,
    seccion_id     UUID        NOT NULL REFERENCES seccion_actividad(id) ON DELETE CASCADE,
    nombre         TEXT        NOT NULL,
    descripcion    TEXT,
    archivo_url    TEXT,
    archivo_tipo   TEXT,
    fecha_inicio   DATE,
    fecha_fin      DATE,
    orden          INTEGER     NOT NULL DEFAULT 0,
    creado_en      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_sub_seccion_actividad_seccion_id ON sub_seccion_actividad (seccion_id);


-- Guías adjuntas directamente a una actividad de proyecto (para el instructor).
CREATE TABLE IF NOT EXISTS guia_actividad_proyecto (
    id                    UUID        PRIMARY KEY,
    actividad_proyecto_id UUID        NOT NULL REFERENCES actividad_proyecto(id) ON DELETE CASCADE,
    nombre                TEXT,
    descripcion           TEXT,
    url                   TEXT        NOT NULL,
    orden                 INTEGER     NOT NULL DEFAULT 0,
    subido_en             TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    creado_en             TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en        TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_guia_actividad_proyecto_actividad_proyecto_id ON guia_actividad_proyecto (actividad_proyecto_id);

-- ============================================================
-- PROGRAMS & FICHAS
-- ============================================================

-- Programa de formación: combinación de área y nivel.
-- No se puede eliminar un área o nivel con programas asociados (RESTRICT).
CREATE TABLE IF NOT EXISTS programa_formacion (
    id                  UUID        PRIMARY KEY,
    area_id             UUID        NOT NULL REFERENCES area(id) ON DELETE RESTRICT,
    nivel_formacion_id  UUID        NOT NULL REFERENCES nivel_formacion(id) ON DELETE RESTRICT,
    nombre              TEXT        NOT NULL,
    creado_en           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en      TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_programa_formacion_area_id            ON programa_formacion (area_id);
CREATE INDEX IF NOT EXISTS idx_programa_formacion_nivel_formacion_id ON programa_formacion (nivel_formacion_id);


-- Ficha de formación: grupo de aprendices en un programa.
-- No se puede eliminar el programa o coordinación si tiene fichas (RESTRICT).
-- El proyecto formativo e instructor son opcionales (SET NULL).
CREATE TABLE IF NOT EXISTS ficha_formacion (
    id                    UUID        PRIMARY KEY,
    numero                TEXT        NOT NULL UNIQUE,
    programa_formacion_id UUID        NOT NULL REFERENCES programa_formacion(id) ON DELETE RESTRICT,
    proyecto_formativo_id UUID        REFERENCES proyecto_formativo(id) ON DELETE SET NULL,
    coordinacion_id       UUID        NOT NULL REFERENCES coordinacion(id) ON DELETE RESTRICT,
    instructor_id         UUID        REFERENCES instructor(id) ON DELETE SET NULL,
    creado_en             TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en        TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_ficha_formacion_programa_formacion_id ON ficha_formacion (programa_formacion_id);
CREATE INDEX IF NOT EXISTS idx_ficha_formacion_proyecto_formativo_id ON ficha_formacion (proyecto_formativo_id);
CREATE INDEX IF NOT EXISTS idx_ficha_formacion_coordinacion_id       ON ficha_formacion (coordinacion_id);
CREATE INDEX IF NOT EXISTS idx_ficha_formacion_instructor_id         ON ficha_formacion (instructor_id);


-- Competencias asignadas: qué instructores dictan qué fichas.
-- Se elimina en cascada si se elimina la ficha o el instructor.
CREATE TABLE IF NOT EXISTS ficha_instructor_competencia (
    id             UUID        PRIMARY KEY,
    ficha_id       UUID        NOT NULL REFERENCES ficha_formacion(id) ON DELETE CASCADE,
    instructor_id  UUID        NOT NULL REFERENCES instructor(id) ON DELETE CASCADE,
    creado_en      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ,
    UNIQUE (ficha_id, instructor_id)
);

CREATE INDEX IF NOT EXISTS idx_ficha_instructor_competencia_ficha_id      ON ficha_instructor_competencia (ficha_id);
CREATE INDEX IF NOT EXISTS idx_ficha_instructor_competencia_instructor_id ON ficha_instructor_competencia (instructor_id);


-- Registro de asistencia de aprendices por ficha y fecha.
CREATE TABLE IF NOT EXISTS asistencia_aprendiz (
    id             UUID        PRIMARY KEY,
    ficha_id       UUID        NOT NULL REFERENCES ficha_formacion(id) ON DELETE CASCADE,
    aprendiz_id    UUID        NOT NULL REFERENCES aprendiz(id) ON DELETE CASCADE,
    fecha          DATE        NOT NULL,
    estado         TEXT        NOT NULL DEFAULT 'Presente',
    creado_en      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ,
    UNIQUE (ficha_id, aprendiz_id, fecha)
);

CREATE INDEX IF NOT EXISTS idx_asistencia_aprendiz_ficha_id    ON asistencia_aprendiz (ficha_id);
CREATE INDEX IF NOT EXISTS idx_asistencia_aprendiz_aprendiz_id ON asistencia_aprendiz (aprendiz_id);

-- ============================================================
-- LEARNER-FACING EXTRAS
-- ============================================================

-- Fases del proceso formativo SENA (Análisis, Planeación, Ejecución…).
-- Tabla de catálogo independiente, distinta de fase_proyecto.
CREATE TABLE IF NOT EXISTS fase (
    id             UUID         PRIMARY KEY,
    nombre         VARCHAR(150) NOT NULL,
    orden          SMALLINT     NOT NULL DEFAULT 1,
    descripcion    TEXT,
    creado_en      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ
);


-- Notificaciones para cualquier usuario del sistema.
-- Se eliminan en cascada al eliminar el usuario.
CREATE TABLE IF NOT EXISTS notificacion (
    id             UUID        PRIMARY KEY,
    usuario_id     UUID        NOT NULL REFERENCES usuario(id) ON DELETE CASCADE,
    mensaje        TEXT        NOT NULL,
    tipo           VARCHAR(10) NOT NULL DEFAULT 'info'
                       CHECK (tipo IN ('info', 'success', 'warning', 'danger')),
    leida          BOOLEAN     NOT NULL DEFAULT FALSE,
    url_destino    TEXT,
    creado_en      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_notificacion_usuario_id ON notificacion (usuario_id);

-- ============================================================
-- SEED DATA
-- ============================================================

INSERT INTO perfil (id, nombre, descripcion) VALUES
    (gen_random_uuid(), 'Administrador',  'Gestión de usuarios, estructura institucional y académica.'),
    (gen_random_uuid(), 'Administrativo', 'Apoyo académico y operativo: fichas, programas y ambientes.'),
    (gen_random_uuid(), 'Instructor',     'Ejecución formativa: fichas, fases, actividades y calificaciones.'),
    (gen_random_uuid(), 'Aprendiz',       'Ruta de aprendizaje: fichas, evidencias y calificaciones.')
ON CONFLICT (nombre) DO NOTHING;

INSERT INTO nivel_formacion (id, nombre) VALUES
    (gen_random_uuid(), 'Técnico'),
    (gen_random_uuid(), 'Tecnólogo'),
    (gen_random_uuid(), 'Operario'),
    (gen_random_uuid(), 'Auxiliar'),
    (gen_random_uuid(), 'Curso')
ON CONFLICT (nombre) DO NOTHING;

INSERT INTO fase (id, nombre, orden, descripcion) VALUES
    (gen_random_uuid(), 'Análisis',   1, 'Identificación del proyecto formativo y reconocimiento del entorno productivo.'),
    (gen_random_uuid(), 'Planeación', 2, 'Diseño y estructuración de las actividades del proyecto formativo.'),
    (gen_random_uuid(), 'Ejecución',  3, 'Desarrollo de las actividades y entrega de evidencias de aprendizaje.')
ON CONFLICT DO NOTHING;

-- Seed users (argon2 hashes must be regenerated by running the app seed once).
-- Passwords: Admin123* / Adminvo123* / Instructor123* / Aprendiz123*
INSERT INTO usuario (id, correo, contrasena_hash, nombre, activo) VALUES
    ('00000000-0000-0000-0000-000000000001', 'admin@senalearn.edu.co',          'REPLACE_WITH_ARGON2_HASH', 'Laura Moreno',  TRUE),
    ('00000000-0000-0000-0000-000000000002', 'administrativo@senalearn.edu.co', 'REPLACE_WITH_ARGON2_HASH', 'Carlos Ruiz',   TRUE),
    ('00000000-0000-0000-0000-000000000003', 'instructor@senalearn.edu.co',     'REPLACE_WITH_ARGON2_HASH', 'Diana Beltrán', TRUE),
    ('00000000-0000-0000-0000-000000000004', 'aprendiz@senalearn.edu.co',       'REPLACE_WITH_ARGON2_HASH', 'Miguel Torres', TRUE)
ON CONFLICT (correo) DO NOTHING;

-- Assign each seed user to its profile
INSERT INTO usuario_perfil (id, usuario_id, perfil_id)
SELECT gen_random_uuid(), u.id, p.id
FROM (VALUES
    ('admin@senalearn.edu.co',          'Administrador'),
    ('administrativo@senalearn.edu.co', 'Administrativo'),
    ('instructor@senalearn.edu.co',     'Instructor'),
    ('aprendiz@senalearn.edu.co',       'Aprendiz')
) AS mapping(correo, perfil_nombre)
JOIN usuario  u ON u.correo    = mapping.correo
JOIN perfil   p ON p.nombre    = mapping.perfil_nombre
ON CONFLICT (usuario_id, perfil_id) DO NOTHING;

COMMIT;
