-- ============================================================
-- Project    : bariLMS — Learning Management System (SENA)
-- File       : database/bari_lms_postgresql.sql
-- Description: Canonical PostgreSQL schema for bariLMS.
--              Supersedes database/setup_aprendiz.sql (legacy).
--
-- PostgreSQL : Requires PostgreSQL 17+
--
-- How to apply:
--   1. psql -U <user> -d <dbname> -f database/bari_lms_postgresql.sql
--   2. psql -U <user> -d <dbname> -f database/seed.sql
--   (safe to re-run; all DDL uses IF NOT EXISTS)
--
-- ── UUID ────────────────────────────────────────────────────
--   UUID v7 generated by the application layer.
--   No DEFAULT on id columns — the app always provides them.
--   sesion.id doubles as the jti claim for BOTH the access token
--   and the refresh token (same UUID v7). Invalidating the session
--   row revokes both tokens simultaneously.
--
-- ── actualizado_en ──────────────────────────────────────────
--   NULL until the first UPDATE. Set by the app on every UPDATE.
--
-- ── creado_por ──────────────────────────────────────────────
--   NULL for the provisional admin and catalog rows.
--   ON DELETE SET NULL — audit rows are never orphaned.
--
-- ── COLLATE "C" ─────────────────────────────────────────────
--   Applied to codes, hashes, emails and document numbers
--   (ASCII / lowercase). Gives byte-order index scans (faster,
--   locale-free). Spanish free-text columns use the DB default
--   collation for correct locale sort.
--
-- ── Case rules (enforced by CHECK) ──────────────────────────
--   correo_institucional, correo_personal → always lower().
--   usuario.nombre, persona.nombres, persona.apellidos → upper().
--
-- ── Persons & accounts ──────────────────────────────────────
--   usuario   — authentication anchor (credentials, display name).
--               The provisional admin lives here without a persona row.
--   persona   — personal/identity data for real people.
--               persona.usuario_id NOT NULL UNIQUE: always linked to a
--               user account; one account = one persona.
--               correo_personal lives here (not in usuario).
--   instructor, aprendiz, personal_administrativo — role-specific data.
--               Each links to persona (persona_id NOT NULL UNIQUE).
--               No direct usuario_id: reach the account via persona.
--
-- ── Dashboard routing (app layer) ───────────────────────────
--   /dashboard → single profile: redirect to perfil.ruta_dashboard.
--                multiple profiles: show selector first.
--   /dashboard/<slug> → blocked unless usuario_perfil links the
--   authenticated user to that perfil.
--
-- ── JWT / cookies (app layer) ───────────────────────────────
--   Cookies: HttpOnly, Secure, SameSite=Strict.
--   access_token  : 15 min, JWT typ=access, NOT stored in DB.
--   refresh_token : 1 day,  JWT typ=refresh, Argon2 hash in sesion.
--   Both tokens carry the same jti = sesion.id (UUID v7).
--   Validation (access):  sig → typ → exp → sesion activo.
--   Validation (refresh): sig → typ → exp → sesion activo → Argon2.
--   Hash mismatch on refresh → revoke with tipo=token_reutilizado.
--   On success: rotate hash, issue new access token.
--
-- ── Provisional admin (app layer) ───────────────────────────
--   On startup with no Administrador user: create one usuario row
--   with random correo_institucional + random password, print to
--   stdout once. No persona row is created for it.
--
-- ── Tables (dependency order) ───────────────────────────────
--   Catalogs : tipo_documento, tipo_invalidacion_sesion
--   Auth     : usuario, persona, sesion, sesion_historial
--   Access   : perfil, rol, permiso, rol_permiso,
--              usuario_perfil, usuario_rol
--   Structure: regional, centro, coordinacion, sede, ambiente
--   Knowledge: red_conocimiento, area, nivel_formacion
--   People   : instructor, aprendiz, personal_administrativo
--   Content  : proyecto_formativo, fase_proyecto, actividad_proyecto,
--              actividad_aprendizaje, guia_aprendizaje,
--              evidencia_aprendizaje, entrega_evidencia,
--              seccion_actividad, sub_seccion_actividad,
--              guia_actividad_proyecto
--   Programs : programa_formacion, ficha_formacion,
--              ficha_instructor_competencia, asistencia_aprendiz
--   Extras   : fase, notificacion
-- ============================================================

BEGIN;

-- ============================================================
-- CATALOGS
-- ============================================================

-- Tipos de documento de identidad colombianos.
CREATE TABLE IF NOT EXISTS tipo_documento (
    -- identity
    id             UUID        PRIMARY KEY,

    -- code & display
    codigo         TEXT        COLLATE "C" NOT NULL UNIQUE,
    nombre         TEXT        NOT NULL,
    descripcion    TEXT,

    -- state
    activo         BOOLEAN     NOT NULL DEFAULT TRUE,

    -- timestamps
    creado_en      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_tipo_documento_codigo ON tipo_documento (codigo);


-- Catálogo de motivos de invalidación de sesión.
CREATE TABLE IF NOT EXISTS tipo_invalidacion_sesion (
    -- identity
    id             UUID        PRIMARY KEY,

    -- code & display
    codigo         TEXT        COLLATE "C" NOT NULL UNIQUE,
    nombre         TEXT        NOT NULL,
    descripcion    TEXT,

    -- timestamps
    creado_en      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_tipo_invalidacion_sesion_codigo ON tipo_invalidacion_sesion (codigo);

-- ============================================================
-- AUTH
-- ============================================================

-- Entidad de autenticación. Todos los perfiles tienen una fila aquí.
-- El admin provisional vive aquí sin fila en persona.
CREATE TABLE IF NOT EXISTS usuario (
    -- identity
    id                   UUID        PRIMARY KEY,

    -- audit
    creado_por           UUID        REFERENCES usuario(id) ON DELETE SET NULL,

    -- credentials (login — correo_personal vive en persona)
    correo_institucional TEXT        COLLATE "C" UNIQUE NOT NULL,
    contrasena_hash      TEXT        NOT NULL,

    -- display name (fallback cuando no hay persona; siempre en mayúsculas)
    nombre               TEXT        NOT NULL,

    -- state
    activo               BOOLEAN     NOT NULL DEFAULT TRUE,

    -- timestamps
    creado_en            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en       TIMESTAMPTZ,

    -- constraints
    CHECK (correo_institucional = lower(correo_institucional)),
    CHECK (nombre = upper(nombre))
);

CREATE INDEX IF NOT EXISTS idx_usuario_correo_institucional ON usuario (correo_institucional);
CREATE INDEX IF NOT EXISTS idx_usuario_creado_por           ON usuario (creado_por);


-- Información personal de los usuarios reales del sistema.
-- usuario_id NOT NULL UNIQUE: relación 1:1 con usuario.
-- Apunta a usuario (no al revés) porque usuario puede existir sin persona
-- (admin provisional), pero persona siempre pertenece a un usuario.
CREATE TABLE IF NOT EXISTS persona (
    -- identity
    id                UUID        PRIMARY KEY,

    -- link to auth account (1:1, obligatorio)
    usuario_id        UUID        NOT NULL UNIQUE REFERENCES usuario(id) ON DELETE RESTRICT,

    -- audit
    creado_por        UUID        REFERENCES usuario(id) ON DELETE SET NULL,

    -- identification document
    tipo_documento_id UUID        REFERENCES tipo_documento(id) ON DELETE RESTRICT,
    numero_documento  TEXT        COLLATE "C",

    -- personal info
    nombres           TEXT        NOT NULL,
    apellidos         TEXT        NOT NULL,
    genero            TEXT,
    fecha_nacimiento  DATE,

    -- contact (correo personal vive aquí, no en usuario)
    correo_personal   TEXT        COLLATE "C",

    -- timestamps
    creado_en         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en    TIMESTAMPTZ,

    -- constraints
    CHECK (nombres   = upper(nombres)),
    CHECK (apellidos = upper(apellidos)),
    CHECK (correo_personal IS NULL OR correo_personal = lower(correo_personal))
);

CREATE INDEX IF NOT EXISTS idx_persona_usuario_id        ON persona (usuario_id);
CREATE INDEX IF NOT EXISTS idx_persona_tipo_documento_id ON persona (tipo_documento_id);
CREATE INDEX IF NOT EXISTS idx_persona_creado_por        ON persona (creado_por);


-- Sesiones activas. sesion.id (UUID v7) es el jti de ambos tokens.
CREATE TABLE IF NOT EXISTS sesion (
    -- identity (= jti para access token y refresh token)
    id                   UUID        PRIMARY KEY,

    -- owner
    usuario_id           UUID        NOT NULL REFERENCES usuario(id) ON DELETE CASCADE,

    -- invalidation (NULL mientras activo)
    tipo_invalidacion_id UUID        REFERENCES tipo_invalidacion_sesion(id) ON DELETE RESTRICT,
    invalidado_en        TIMESTAMPTZ,

    -- refresh token (Argon2 del valor real; COLLATE "C" para hash ASCII)
    refresh_token_hash   TEXT        COLLATE "C" NOT NULL UNIQUE,

    -- client info
    ip_address           TEXT,
    user_agent           TEXT,

    -- state & expiry
    activo               BOOLEAN     NOT NULL DEFAULT TRUE,
    expira_en            TIMESTAMPTZ NOT NULL,

    -- timestamps
    creado_en            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en       TIMESTAMPTZ,

    -- sesión inactiva debe tener siempre motivo y timestamp
    CHECK (
        (activo = TRUE  AND tipo_invalidacion_id IS NULL     AND invalidado_en IS NULL)     OR
        (activo = FALSE AND tipo_invalidacion_id IS NOT NULL AND invalidado_en IS NOT NULL)
    )
);

CREATE INDEX IF NOT EXISTS idx_sesion_usuario_id         ON sesion (usuario_id);
CREATE INDEX IF NOT EXISTS idx_sesion_refresh_token_hash ON sesion (refresh_token_hash);
CREATE INDEX IF NOT EXISTS idx_sesion_activo_expira      ON sesion (activo, expira_en);
CREATE INDEX IF NOT EXISTS idx_sesion_tipo_invalidacion  ON sesion (tipo_invalidacion_id);


-- Log inmutable de eventos de sesión. Nunca se borra.
-- sesion_id → SET NULL si la sesión es eliminada; el historial persiste.
CREATE TABLE IF NOT EXISTS sesion_historial (
    -- identity
    id         UUID        PRIMARY KEY,

    -- links (sesion_id puede quedar NULL si la sesión se elimina)
    sesion_id  UUID        REFERENCES sesion(id) ON DELETE SET NULL,
    usuario_id UUID        NOT NULL REFERENCES usuario(id) ON DELETE CASCADE,

    -- event
    evento     TEXT        NOT NULL
                   CHECK (evento IN (
                       'login',
                       'logout',
                       'token_refresh',
                       'token_expired',
                       'revoked'
                   )),

    -- client info (snapshot al momento del evento)
    ip_address TEXT,
    user_agent TEXT,

    -- timestamp (sin actualizado_en: log inmutable)
    creado_en  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_sesion_historial_sesion_id  ON sesion_historial (sesion_id);
CREATE INDEX IF NOT EXISTS idx_sesion_historial_usuario_id ON sesion_historial (usuario_id);
CREATE INDEX IF NOT EXISTS idx_sesion_historial_creado_en  ON sesion_historial (creado_en);

-- ============================================================
-- ACCESS CONTROL
-- ============================================================

-- Perfiles del sistema con su ruta exclusiva de dashboard.
CREATE TABLE IF NOT EXISTS perfil (
    -- identity
    id             UUID        PRIMARY KEY,

    -- display
    nombre         TEXT        NOT NULL UNIQUE,
    descripcion    TEXT,

    -- routing
    ruta_dashboard TEXT        NOT NULL,

    -- audit
    creado_por     UUID        REFERENCES usuario(id) ON DELETE SET NULL,

    -- timestamps
    creado_en      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_perfil_creado_por ON perfil (creado_por);


-- Roles granulares dentro de un perfil.
CREATE TABLE IF NOT EXISTS rol (
    -- identity
    id             UUID        PRIMARY KEY,

    -- parent
    perfil_id      UUID        NOT NULL REFERENCES perfil(id) ON DELETE CASCADE,

    -- display
    nombre         TEXT        NOT NULL,
    descripcion    TEXT,

    -- audit
    creado_por     UUID        REFERENCES usuario(id) ON DELETE SET NULL,

    -- timestamps
    creado_en      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ,

    UNIQUE (perfil_id, nombre)
);

CREATE INDEX IF NOT EXISTS idx_rol_perfil_id  ON rol (perfil_id);
CREATE INDEX IF NOT EXISTS idx_rol_creado_por ON rol (creado_por);


-- Permisos atómicos. codigo: recurso.accion (ej: fichas.ver).
CREATE TABLE IF NOT EXISTS permiso (
    -- identity
    id             UUID        PRIMARY KEY,

    -- code & display
    codigo         TEXT        COLLATE "C" NOT NULL UNIQUE,
    nombre         TEXT        NOT NULL,
    descripcion    TEXT,

    -- audit
    creado_por     UUID        REFERENCES usuario(id) ON DELETE SET NULL,

    -- timestamps
    creado_en      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_permiso_codigo     ON permiso (codigo);
CREATE INDEX IF NOT EXISTS idx_permiso_creado_por ON permiso (creado_por);


-- Permisos asignados a un rol.
CREATE TABLE IF NOT EXISTS rol_permiso (
    -- identity
    id             UUID        PRIMARY KEY,

    -- links
    rol_id         UUID        NOT NULL REFERENCES rol(id)     ON DELETE CASCADE,
    permiso_id     UUID        NOT NULL REFERENCES permiso(id) ON DELETE CASCADE,

    -- audit
    creado_por     UUID        REFERENCES usuario(id) ON DELETE SET NULL,

    -- timestamps
    creado_en      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ,

    UNIQUE (rol_id, permiso_id)
);

CREATE INDEX IF NOT EXISTS idx_rol_permiso_rol_id     ON rol_permiso (rol_id);
CREATE INDEX IF NOT EXISTS idx_rol_permiso_permiso_id ON rol_permiso (permiso_id);


-- Perfiles asignados a un usuario (pivote muchos-a-muchos).
CREATE TABLE IF NOT EXISTS usuario_perfil (
    -- identity
    id             UUID        PRIMARY KEY,

    -- links
    usuario_id     UUID        NOT NULL REFERENCES usuario(id) ON DELETE CASCADE,
    perfil_id      UUID        NOT NULL REFERENCES perfil(id)  ON DELETE CASCADE,

    -- audit
    creado_por     UUID        REFERENCES usuario(id) ON DELETE SET NULL,

    -- timestamps
    creado_en      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ,

    UNIQUE (usuario_id, perfil_id)
);

CREATE INDEX IF NOT EXISTS idx_usuario_perfil_usuario_id ON usuario_perfil (usuario_id);
CREATE INDEX IF NOT EXISTS idx_usuario_perfil_perfil_id  ON usuario_perfil (perfil_id);


-- Roles asignados a un usuario.
CREATE TABLE IF NOT EXISTS usuario_rol (
    -- identity
    id             UUID        PRIMARY KEY,

    -- links
    usuario_id     UUID        NOT NULL REFERENCES usuario(id) ON DELETE CASCADE,
    rol_id         UUID        NOT NULL REFERENCES rol(id)     ON DELETE CASCADE,

    -- audit
    creado_por     UUID        REFERENCES usuario(id) ON DELETE SET NULL,

    -- timestamps
    creado_en      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ,

    UNIQUE (usuario_id, rol_id)
);

CREATE INDEX IF NOT EXISTS idx_usuario_rol_usuario_id ON usuario_rol (usuario_id);
CREATE INDEX IF NOT EXISTS idx_usuario_rol_rol_id     ON usuario_rol (rol_id);

-- ============================================================
-- INSTITUTIONAL STRUCTURE
-- ============================================================

-- Regionales del SENA. Nivel más alto de la jerarquía institucional.
CREATE TABLE IF NOT EXISTS regional (
    -- identity
    id             UUID        PRIMARY KEY,

    -- display
    nombre         TEXT        NOT NULL UNIQUE,

    -- audit
    creado_por     UUID        REFERENCES usuario(id) ON DELETE SET NULL,

    -- timestamps
    creado_en      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_regional_creado_por ON regional (creado_por);


-- Centros de formación. No se elimina una regional con centros (RESTRICT).
CREATE TABLE IF NOT EXISTS centro (
    -- identity
    id             UUID        PRIMARY KEY,

    -- parent
    regional_id    UUID        NOT NULL REFERENCES regional(id) ON DELETE RESTRICT,

    -- display
    nombre         TEXT        NOT NULL,

    -- audit
    creado_por     UUID        REFERENCES usuario(id) ON DELETE SET NULL,

    -- timestamps
    creado_en      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_centro_regional_id ON centro (regional_id);
CREATE INDEX IF NOT EXISTS idx_centro_creado_por  ON centro (creado_por);


-- Coordinaciones académicas dentro de un centro.
CREATE TABLE IF NOT EXISTS coordinacion (
    -- identity
    id             UUID        PRIMARY KEY,

    -- parent
    centro_id      UUID        NOT NULL REFERENCES centro(id) ON DELETE RESTRICT,

    -- display
    nombre         TEXT        NOT NULL,

    -- audit
    creado_por     UUID        REFERENCES usuario(id) ON DELETE SET NULL,

    -- timestamps
    creado_en      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_coordinacion_centro_id  ON coordinacion (centro_id);
CREATE INDEX IF NOT EXISTS idx_coordinacion_creado_por ON coordinacion (creado_por);


-- Sedes físicas dentro de un centro.
CREATE TABLE IF NOT EXISTS sede (
    -- identity
    id             UUID        PRIMARY KEY,

    -- parent
    centro_id      UUID        NOT NULL REFERENCES centro(id) ON DELETE RESTRICT,

    -- display
    nombre         TEXT        NOT NULL,

    -- audit
    creado_por     UUID        REFERENCES usuario(id) ON DELETE SET NULL,

    -- timestamps
    creado_en      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_sede_centro_id  ON sede (centro_id);
CREATE INDEX IF NOT EXISTS idx_sede_creado_por ON sede (creado_por);


-- Ambientes o aulas dentro de una sede.
CREATE TABLE IF NOT EXISTS ambiente (
    -- identity
    id             UUID        PRIMARY KEY,

    -- parent
    sede_id        UUID        NOT NULL REFERENCES sede(id) ON DELETE RESTRICT,

    -- display
    nombre         TEXT        NOT NULL,
    capacidad      INTEGER,

    -- audit
    creado_por     UUID        REFERENCES usuario(id) ON DELETE SET NULL,

    -- timestamps
    creado_en      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_ambiente_sede_id    ON ambiente (sede_id);
CREATE INDEX IF NOT EXISTS idx_ambiente_creado_por ON ambiente (creado_por);

-- ============================================================
-- ACADEMIC KNOWLEDGE STRUCTURE
-- ============================================================

-- Redes de conocimiento del SENA (ej: Tecnología, Agroindustria).
CREATE TABLE IF NOT EXISTS red_conocimiento (
    -- identity
    id             UUID        PRIMARY KEY,

    -- display
    nombre         TEXT        NOT NULL UNIQUE,

    -- audit
    creado_por     UUID        REFERENCES usuario(id) ON DELETE SET NULL,

    -- timestamps
    creado_en      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_red_conocimiento_creado_por ON red_conocimiento (creado_por);


-- Áreas de desempeño dentro de una red de conocimiento.
CREATE TABLE IF NOT EXISTS area (
    -- identity
    id                   UUID        PRIMARY KEY,

    -- parent
    red_conocimiento_id  UUID        NOT NULL REFERENCES red_conocimiento(id) ON DELETE RESTRICT,

    -- display
    nombre               TEXT        NOT NULL,

    -- audit
    creado_por           UUID        REFERENCES usuario(id) ON DELETE SET NULL,

    -- timestamps
    creado_en            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en       TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_area_red_conocimiento_id ON area (red_conocimiento_id);
CREATE INDEX IF NOT EXISTS idx_area_creado_por          ON area (creado_por);


-- Niveles de formación (Técnico, Tecnólogo, Operario, etc.).
CREATE TABLE IF NOT EXISTS nivel_formacion (
    -- identity
    id             UUID        PRIMARY KEY,

    -- display
    nombre         TEXT        NOT NULL UNIQUE,

    -- audit
    creado_por     UUID        REFERENCES usuario(id) ON DELETE SET NULL,

    -- timestamps
    creado_en      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_nivel_formacion_creado_por ON nivel_formacion (creado_por);

-- ============================================================
-- PEOPLE
-- ============================================================
-- Cada tabla de persona lleva persona_id NOT NULL UNIQUE.
-- persona.usuario_id lleva al usuario con las credenciales.
-- No se repite usuario_id aquí: se accede vía persona.
-- ============================================================

-- Instructores vinculados a un centro y opcionalmente a un área.
-- No se puede eliminar un centro o área con instructores activos (RESTRICT).
CREATE TABLE IF NOT EXISTS instructor (
    -- identity
    id          UUID        PRIMARY KEY,

    -- person (1:1 — un instructor = una persona)
    persona_id  UUID        NOT NULL UNIQUE REFERENCES persona(id) ON DELETE RESTRICT,

    -- institutional
    centro_id   UUID        NOT NULL REFERENCES centro(id) ON DELETE RESTRICT,
    area_id     UUID        REFERENCES area(id) ON DELETE SET NULL,

    -- audit
    creado_por  UUID        REFERENCES usuario(id) ON DELETE SET NULL,

    -- timestamps
    creado_en      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_instructor_persona_id ON instructor (persona_id);
CREATE INDEX IF NOT EXISTS idx_instructor_centro_id  ON instructor (centro_id);
CREATE INDEX IF NOT EXISTS idx_instructor_area_id    ON instructor (area_id);
CREATE INDEX IF NOT EXISTS idx_instructor_creado_por ON instructor (creado_por);


-- Aprendices vinculados a una regional.
-- No se puede eliminar una regional con aprendices (RESTRICT).
CREATE TABLE IF NOT EXISTS aprendiz (
    -- identity
    id          UUID        PRIMARY KEY,

    -- person (1:1)
    persona_id  UUID        NOT NULL UNIQUE REFERENCES persona(id) ON DELETE RESTRICT,

    -- institutional
    regional_id UUID        NOT NULL REFERENCES regional(id) ON DELETE RESTRICT,

    -- academic
    ficha       TEXT,

    -- audit
    creado_por  UUID        REFERENCES usuario(id) ON DELETE SET NULL,

    -- timestamps
    creado_en      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_aprendiz_persona_id  ON aprendiz (persona_id);
CREATE INDEX IF NOT EXISTS idx_aprendiz_regional_id ON aprendiz (regional_id);
CREATE INDEX IF NOT EXISTS idx_aprendiz_creado_por  ON aprendiz (creado_por);


-- Personal administrativo vinculado a un centro.
-- No se puede eliminar un centro con personal administrativo (RESTRICT).
CREATE TABLE IF NOT EXISTS personal_administrativo (
    -- identity
    id          UUID        PRIMARY KEY,

    -- person (1:1)
    persona_id  UUID        NOT NULL UNIQUE REFERENCES persona(id) ON DELETE RESTRICT,

    -- institutional
    centro_id   UUID        NOT NULL REFERENCES centro(id) ON DELETE RESTRICT,

    -- role-specific
    cargo       TEXT        NOT NULL,

    -- audit
    creado_por  UUID        REFERENCES usuario(id) ON DELETE SET NULL,

    -- timestamps
    creado_en      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_personal_administrativo_persona_id ON personal_administrativo (persona_id);
CREATE INDEX IF NOT EXISTS idx_personal_administrativo_centro_id  ON personal_administrativo (centro_id);
CREATE INDEX IF NOT EXISTS idx_personal_administrativo_creado_por ON personal_administrativo (creado_por);

-- ============================================================
-- ACADEMIC CONTENT CHAIN
-- ============================================================

-- Proyecto formativo: documento guía del proceso de formación.
CREATE TABLE IF NOT EXISTS proyecto_formativo (
    -- identity
    id             UUID        PRIMARY KEY,

    -- code & display
    codigo         TEXT        COLLATE "C" NOT NULL UNIQUE,
    nombre         TEXT        NOT NULL,

    -- audit
    creado_por     UUID        REFERENCES usuario(id) ON DELETE SET NULL,

    -- timestamps
    creado_en      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_proyecto_formativo_creado_por ON proyecto_formativo (creado_por);


-- Fases del proyecto formativo (ej: Análisis, Planeación, Ejecución).
CREATE TABLE IF NOT EXISTS fase_proyecto (
    -- identity
    id                    UUID        PRIMARY KEY,

    -- parent
    proyecto_formativo_id UUID        NOT NULL REFERENCES proyecto_formativo(id) ON DELETE CASCADE,

    -- display
    nombre                TEXT        NOT NULL,

    -- audit
    creado_por            UUID        REFERENCES usuario(id) ON DELETE SET NULL,

    -- timestamps
    creado_en             TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en        TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_fase_proyecto_proyecto_formativo_id ON fase_proyecto (proyecto_formativo_id);
CREATE INDEX IF NOT EXISTS idx_fase_proyecto_creado_por            ON fase_proyecto (creado_por);


-- Actividades del proyecto agrupadas por fase.
CREATE TABLE IF NOT EXISTS actividad_proyecto (
    -- identity
    id               UUID        PRIMARY KEY,

    -- parent
    fase_proyecto_id UUID        NOT NULL REFERENCES fase_proyecto(id) ON DELETE CASCADE,

    -- display
    nombre           TEXT        NOT NULL,

    -- audit
    creado_por       UUID        REFERENCES usuario(id) ON DELETE SET NULL,

    -- timestamps
    creado_en        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en   TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_actividad_proyecto_fase_proyecto_id ON actividad_proyecto (fase_proyecto_id);
CREATE INDEX IF NOT EXISTS idx_actividad_proyecto_creado_por       ON actividad_proyecto (creado_por);


-- Actividades de aprendizaje dentro de una actividad de proyecto.
CREATE TABLE IF NOT EXISTS actividad_aprendizaje (
    -- identity
    id                    UUID        PRIMARY KEY,

    -- parent
    actividad_proyecto_id UUID        NOT NULL REFERENCES actividad_proyecto(id) ON DELETE CASCADE,

    -- display
    nombre                TEXT        NOT NULL,
    descripcion           TEXT,

    -- scheduling
    fecha_inicio          DATE,
    fecha_fin             DATE,
    orden                 INTEGER     NOT NULL DEFAULT 0,

    -- audit
    creado_por            UUID        REFERENCES usuario(id) ON DELETE SET NULL,

    -- timestamps
    creado_en             TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en        TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_actividad_aprendizaje_actividad_proyecto_id ON actividad_aprendizaje (actividad_proyecto_id);
CREATE INDEX IF NOT EXISTS idx_actividad_aprendizaje_creado_por            ON actividad_aprendizaje (creado_por);


-- Guía de aprendizaje adjunta a una actividad (1:1).
CREATE TABLE IF NOT EXISTS guia_aprendizaje (
    -- identity
    id                       UUID        PRIMARY KEY,

    -- parent (1:1)
    actividad_aprendizaje_id UUID        NOT NULL UNIQUE
                                 REFERENCES actividad_aprendizaje(id) ON DELETE CASCADE,

    -- content
    url                      TEXT        NOT NULL,
    subido_en                TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- audit
    creado_por               UUID        REFERENCES usuario(id) ON DELETE SET NULL,

    -- timestamps
    creado_en                TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en           TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_guia_aprendizaje_actividad_aprendizaje_id ON guia_aprendizaje (actividad_aprendizaje_id);
CREATE INDEX IF NOT EXISTS idx_guia_aprendizaje_creado_por               ON guia_aprendizaje (creado_por);


-- Evidencia de aprendizaje asociada a una actividad (1:1).
CREATE TABLE IF NOT EXISTS evidencia_aprendizaje (
    -- identity
    id                       UUID        PRIMARY KEY,

    -- parent (1:1)
    actividad_aprendizaje_id UUID        NOT NULL UNIQUE
                                 REFERENCES actividad_aprendizaje(id) ON DELETE CASCADE,

    -- display
    descripcion              TEXT,

    -- audit
    creado_por               UUID        REFERENCES usuario(id) ON DELETE SET NULL,

    -- timestamps
    creado_en                TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en           TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_evidencia_aprendizaje_actividad_aprendizaje_id ON evidencia_aprendizaje (actividad_aprendizaje_id);
CREATE INDEX IF NOT EXISTS idx_evidencia_aprendizaje_creado_por               ON evidencia_aprendizaje (creado_por);


-- Entrega de evidencia por un aprendiz, con calificación del instructor.
-- usuario_id (aprendiz que entrega): RESTRICT — no borrar si tiene entregas.
CREATE TABLE IF NOT EXISTS entrega_evidencia (
    -- identity
    id                       UUID        PRIMARY KEY,

    -- links
    evidencia_aprendizaje_id UUID        NOT NULL
                                 REFERENCES evidencia_aprendizaje(id) ON DELETE CASCADE,
    usuario_id               UUID        NOT NULL REFERENCES usuario(id) ON DELETE RESTRICT,

    -- submission
    url                      TEXT,
    entregado_en             TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- grading
    calificacion             NUMERIC(5,2),
    observaciones            TEXT,
    retroalimentacion        TEXT,
    aprueba                  BOOLEAN,
    calificado_en            TIMESTAMPTZ,

    -- audit
    creado_por               UUID        REFERENCES usuario(id) ON DELETE SET NULL,

    -- timestamps
    creado_en                TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en           TIMESTAMPTZ,

    UNIQUE (evidencia_aprendizaje_id, usuario_id)
);

CREATE INDEX IF NOT EXISTS idx_entrega_evidencia_evidencia_aprendizaje_id ON entrega_evidencia (evidencia_aprendizaje_id);
CREATE INDEX IF NOT EXISTS idx_entrega_evidencia_usuario_id               ON entrega_evidencia (usuario_id);
CREATE INDEX IF NOT EXISTS idx_entrega_evidencia_creado_por               ON entrega_evidencia (creado_por);


-- Secciones dentro de una actividad de aprendizaje.
CREATE TABLE IF NOT EXISTS seccion_actividad (
    -- identity
    id                       UUID        PRIMARY KEY,

    -- parent
    actividad_aprendizaje_id UUID        NOT NULL
                                 REFERENCES actividad_aprendizaje(id) ON DELETE CASCADE,

    -- display
    nombre                   TEXT        NOT NULL,
    descripcion              TEXT,

    -- content
    archivo_url              TEXT,
    archivo_tipo             TEXT,

    -- scheduling
    fecha_inicio             DATE,
    fecha_fin                DATE,
    orden                    INTEGER     NOT NULL DEFAULT 0,

    -- audit
    creado_por               UUID        REFERENCES usuario(id) ON DELETE SET NULL,

    -- timestamps
    creado_en                TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en           TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_seccion_actividad_actividad_aprendizaje_id ON seccion_actividad (actividad_aprendizaje_id);
CREATE INDEX IF NOT EXISTS idx_seccion_actividad_creado_por               ON seccion_actividad (creado_por);


-- Subsecciones dentro de una sección de actividad.
CREATE TABLE IF NOT EXISTS sub_seccion_actividad (
    -- identity
    id             UUID        PRIMARY KEY,

    -- parent
    seccion_id     UUID        NOT NULL REFERENCES seccion_actividad(id) ON DELETE CASCADE,

    -- display
    nombre         TEXT        NOT NULL,
    descripcion    TEXT,

    -- content
    archivo_url    TEXT,
    archivo_tipo   TEXT,

    -- scheduling
    fecha_inicio   DATE,
    fecha_fin      DATE,
    orden          INTEGER     NOT NULL DEFAULT 0,

    -- audit
    creado_por     UUID        REFERENCES usuario(id) ON DELETE SET NULL,

    -- timestamps
    creado_en      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_sub_seccion_actividad_seccion_id ON sub_seccion_actividad (seccion_id);
CREATE INDEX IF NOT EXISTS idx_sub_seccion_actividad_creado_por ON sub_seccion_actividad (creado_por);


-- Guías adjuntas a una actividad de proyecto (uso del instructor).
CREATE TABLE IF NOT EXISTS guia_actividad_proyecto (
    -- identity
    id                    UUID        PRIMARY KEY,

    -- parent
    actividad_proyecto_id UUID        NOT NULL
                              REFERENCES actividad_proyecto(id) ON DELETE CASCADE,

    -- display & content
    nombre                TEXT,
    descripcion           TEXT,
    url                   TEXT        NOT NULL,
    orden                 INTEGER     NOT NULL DEFAULT 0,
    subido_en             TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- audit
    creado_por            UUID        REFERENCES usuario(id) ON DELETE SET NULL,

    -- timestamps
    creado_en             TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en        TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_guia_actividad_proyecto_actividad_proyecto_id ON guia_actividad_proyecto (actividad_proyecto_id);
CREATE INDEX IF NOT EXISTS idx_guia_actividad_proyecto_creado_por            ON guia_actividad_proyecto (creado_por);

-- ============================================================
-- PROGRAMS & FICHAS
-- ============================================================

-- Programa de formación: combinación de área y nivel.
CREATE TABLE IF NOT EXISTS programa_formacion (
    -- identity
    id                  UUID        PRIMARY KEY,

    -- parents
    area_id             UUID        NOT NULL REFERENCES area(id)            ON DELETE RESTRICT,
    nivel_formacion_id  UUID        NOT NULL REFERENCES nivel_formacion(id) ON DELETE RESTRICT,

    -- display
    nombre              TEXT        NOT NULL,

    -- audit
    creado_por          UUID        REFERENCES usuario(id) ON DELETE SET NULL,

    -- timestamps
    creado_en           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en      TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_programa_formacion_area_id            ON programa_formacion (area_id);
CREATE INDEX IF NOT EXISTS idx_programa_formacion_nivel_formacion_id ON programa_formacion (nivel_formacion_id);
CREATE INDEX IF NOT EXISTS idx_programa_formacion_creado_por         ON programa_formacion (creado_por);


-- Ficha de formación: cohorte de aprendices en un programa.
CREATE TABLE IF NOT EXISTS ficha_formacion (
    -- identity
    id                    UUID        PRIMARY KEY,
    numero                TEXT        COLLATE "C" NOT NULL UNIQUE,

    -- parents
    programa_formacion_id UUID        NOT NULL REFERENCES programa_formacion(id) ON DELETE RESTRICT,
    coordinacion_id       UUID        NOT NULL REFERENCES coordinacion(id)       ON DELETE RESTRICT,

    -- optional links
    proyecto_formativo_id UUID        REFERENCES proyecto_formativo(id) ON DELETE SET NULL,
    instructor_id         UUID        REFERENCES instructor(id)         ON DELETE SET NULL,

    -- audit
    creado_por            UUID        REFERENCES usuario(id) ON DELETE SET NULL,

    -- timestamps
    creado_en             TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en        TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_ficha_formacion_programa_formacion_id ON ficha_formacion (programa_formacion_id);
CREATE INDEX IF NOT EXISTS idx_ficha_formacion_coordinacion_id       ON ficha_formacion (coordinacion_id);
CREATE INDEX IF NOT EXISTS idx_ficha_formacion_proyecto_formativo_id ON ficha_formacion (proyecto_formativo_id);
CREATE INDEX IF NOT EXISTS idx_ficha_formacion_instructor_id         ON ficha_formacion (instructor_id);
CREATE INDEX IF NOT EXISTS idx_ficha_formacion_creado_por            ON ficha_formacion (creado_por);


-- Instructores asignados a una ficha (competencias).
CREATE TABLE IF NOT EXISTS ficha_instructor_competencia (
    -- identity
    id             UUID        PRIMARY KEY,

    -- links
    ficha_id       UUID        NOT NULL REFERENCES ficha_formacion(id) ON DELETE CASCADE,
    instructor_id  UUID        NOT NULL REFERENCES instructor(id)      ON DELETE CASCADE,

    -- audit
    creado_por     UUID        REFERENCES usuario(id) ON DELETE SET NULL,

    -- timestamps
    creado_en      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ,

    UNIQUE (ficha_id, instructor_id)
);

CREATE INDEX IF NOT EXISTS idx_ficha_instructor_competencia_ficha_id      ON ficha_instructor_competencia (ficha_id);
CREATE INDEX IF NOT EXISTS idx_ficha_instructor_competencia_instructor_id ON ficha_instructor_competencia (instructor_id);
CREATE INDEX IF NOT EXISTS idx_ficha_instructor_competencia_creado_por    ON ficha_instructor_competencia (creado_por);


-- Asistencia de aprendices por ficha y fecha.
CREATE TABLE IF NOT EXISTS asistencia_aprendiz (
    -- identity
    id             UUID        PRIMARY KEY,

    -- links
    ficha_id       UUID        NOT NULL REFERENCES ficha_formacion(id) ON DELETE CASCADE,
    aprendiz_id    UUID        NOT NULL REFERENCES aprendiz(id)        ON DELETE CASCADE,

    -- data
    fecha          DATE        NOT NULL,
    estado         TEXT        NOT NULL DEFAULT 'Presente',

    -- audit
    creado_por     UUID        REFERENCES usuario(id) ON DELETE SET NULL,

    -- timestamps
    creado_en      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ,

    UNIQUE (ficha_id, aprendiz_id, fecha)
);

CREATE INDEX IF NOT EXISTS idx_asistencia_aprendiz_ficha_id    ON asistencia_aprendiz (ficha_id);
CREATE INDEX IF NOT EXISTS idx_asistencia_aprendiz_aprendiz_id ON asistencia_aprendiz (aprendiz_id);
CREATE INDEX IF NOT EXISTS idx_asistencia_aprendiz_creado_por  ON asistencia_aprendiz (creado_por);

-- ============================================================
-- LEARNER-FACING EXTRAS
-- ============================================================

-- Fases del proceso formativo SENA (catálogo independiente).
CREATE TABLE IF NOT EXISTS fase (
    -- identity
    id             UUID         PRIMARY KEY,

    -- display
    nombre         VARCHAR(150) NOT NULL UNIQUE,
    descripcion    TEXT,

    -- ordering
    orden          SMALLINT     NOT NULL DEFAULT 1,

    -- timestamps
    creado_en      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ
);


-- Notificaciones para cualquier usuario del sistema.
CREATE TABLE IF NOT EXISTS notificacion (
    -- identity
    id             UUID        PRIMARY KEY,

    -- owner
    usuario_id     UUID        NOT NULL REFERENCES usuario(id) ON DELETE CASCADE,

    -- content
    mensaje        TEXT        NOT NULL,
    tipo           VARCHAR(10) NOT NULL DEFAULT 'info'
                       CHECK (tipo IN ('info', 'success', 'warning', 'danger')),
    url_destino    TEXT,

    -- state
    leida          BOOLEAN     NOT NULL DEFAULT FALSE,

    -- audit
    creado_por     UUID        REFERENCES usuario(id) ON DELETE SET NULL,

    -- timestamps
    creado_en      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_notificacion_usuario_id ON notificacion (usuario_id);
CREATE INDEX IF NOT EXISTS idx_notificacion_creado_por ON notificacion (creado_por);

COMMIT;
