-- ============================================================
-- Project    : bariLMS — Learning Management System (SENA)
-- File       : database/bari_lms_postgresql.sql
-- Description: Canonical PostgreSQL schema for bariLMS.
--              Supersedes database/setup_aprendiz.sql (legacy).
--
-- PostgreSQL : Requires PostgreSQL 17+
--
-- How to apply:
--   1. psql -U <user> -d <dbname> -f database/bari_lms_postgresql.sql
--   2. psql -U <user> -d <dbname> -f database/seed.sql
--   (safe to re-run; all DDL uses IF NOT EXISTS)
--
-- UUID       : UUID v7 generated by the application layer.
--              No DEFAULT on id columns — the app always provides them.
--              sesion.id doubles as the jti claim for BOTH the access
--              token and the refresh token (same UUID v7). Invalidating
--              the session row revokes both tokens simultaneously.
--
-- actualizado_en : NULL until the first UPDATE. Set by the app on every
--              UPDATE statement.
--
-- creado_por  : NULL for the provisional admin and catalog rows.
--              ON DELETE SET NULL so audit rows are never orphaned.
--
-- COLLATE "C" : Applied to columns that store codes, hashes, emails and
--              document numbers — all ASCII/lowercase — so that index
--              scans use byte-order comparison (faster, locale-free).
--              Spanish free-text columns (nombre, descripcion, etc.) use
--              the database's default collation for correct locale sort.
--
-- Case rules (enforced by CHECK constraints):
--   - correo_institucional, correo_personal : always lower-case.
--   - nombre (usuario), nombres/apellidos (people tables) : always UPPER.
--
-- Provisional admin : The application detects at startup that no user
--   with the 'Administrador' perfil exists and creates one automatically
--   with a random correo_institucional and random password. This is
--   printed to stdout once and never stored in source code.
--
-- JWT cookie security (app layer):
--   - Cookies: HttpOnly, Secure, SameSite=Strict.
--   - access_token  : 15 min, JWT (typ=access), NOT stored in DB.
--   - refresh_token : 1 day, JWT (typ=refresh), hash stored in sesion.
--   - Both tokens carry the same jti = sesion.id (UUID v7).
--   - Validation checklist (access token):
--       1. Verify JWT signature.
--       2. Verify typ == "access".
--       3. Verify exp not expired.
--       4. Look up sesion by jti; verify activo=TRUE and not expired.
--   - Validation checklist (refresh token):
--       1. Verify JWT signature.
--       2. Verify typ == "refresh".
--       3. Verify exp not expired.
--       4. Look up sesion by jti; verify activo=TRUE and not expired.
--       5. Argon2-verify provided token against sesion.refresh_token_hash.
--       6. On success: rotate hash, issue new access token.
--       7. On hash mismatch: mark session revoked with
--          tipo_invalidacion = token_reutilizado (possible theft).
--
-- Dashboard routing (app layer):
--   - /dashboard redirects to perfil.ruta_dashboard if single profile,
--     or shows a selector if the user has multiple profiles.
--   - Each route /dashboard/<slug> is accessible only to users whose
--     usuario_perfil row links them to that perfil.
--
-- Tables (dependency order):
--   Catalogs : tipo_documento, tipo_invalidacion_sesion
--   Auth     : usuario, sesion, sesion_historial
--   Access   : perfil, rol, permiso, rol_permiso,
--              usuario_perfil, usuario_rol
--   Structure: regional, centro, coordinacion, sede, ambiente
--   Knowledge: red_conocimiento, area, nivel_formacion
--   People   : instructor, aprendiz, personal_administrativo
--   Content  : proyecto_formativo, fase_proyecto, actividad_proyecto,
--              actividad_aprendizaje, guia_aprendizaje,
--              evidencia_aprendizaje, entrega_evidencia,
--              seccion_actividad, sub_seccion_actividad,
--              guia_actividad_proyecto
--   Programs : programa_formacion, ficha_formacion,
--              ficha_instructor_competencia, asistencia_aprendiz
--   Extras   : fase, notificacion
-- ============================================================

BEGIN;

-- ============================================================
-- CATALOGS
-- ============================================================

-- Tipos de documento de identidad colombianos.
-- codigo usa COLLATE "C": valores ASCII cortos (CC, TI, CE…).
CREATE TABLE IF NOT EXISTS tipo_documento (
    id             UUID        PRIMARY KEY,
    codigo         TEXT        COLLATE "C" NOT NULL UNIQUE,
    nombre         TEXT        NOT NULL,
    descripcion    TEXT,
    activo         BOOLEAN     NOT NULL DEFAULT TRUE,
    creado_en      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_tipo_documento_codigo ON tipo_documento (codigo);


-- Catálogo de motivos de invalidación de sesión.
-- Permite auditar POR QUÉ se revocó cada sesión.
-- Ejemplos: logout_manual, token_reutilizado, cuenta_desactivada…
CREATE TABLE IF NOT EXISTS tipo_invalidacion_sesion (
    id             UUID        PRIMARY KEY,
    codigo         TEXT        COLLATE "C" NOT NULL UNIQUE,
    nombre         TEXT        NOT NULL,
    descripcion    TEXT,
    creado_en      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_tipo_invalidacion_sesion_codigo ON tipo_invalidacion_sesion (codigo);

-- ============================================================
-- AUTH & SESSIONS
-- ============================================================

-- Usuarios del sistema. Todos los perfiles tienen una fila aquí.
-- correo_institucional : login único (COLLATE "C", siempre lower()).
-- correo_personal      : solo informativo, NUNCA usado en autenticación.
-- nombre               : siempre en MAYÚSCULAS (CHECK).
-- tipo_documento_id    : nullable (el admin provisional puede no tenerlo).
-- numero_documento     : COLLATE "C"; alphanumeric IDs colombianos.
-- creado_por           : NULL para el admin provisional y registros seed.
CREATE TABLE IF NOT EXISTS usuario (
    id                   UUID        PRIMARY KEY,
    creado_por           UUID        REFERENCES usuario(id) ON DELETE SET NULL,
    tipo_documento_id    UUID        REFERENCES tipo_documento(id) ON DELETE RESTRICT,
    numero_documento     TEXT        COLLATE "C",
    correo_institucional TEXT        COLLATE "C" UNIQUE NOT NULL,
    correo_personal      TEXT        COLLATE "C",
    contrasena_hash      TEXT        NOT NULL,
    nombre               TEXT        NOT NULL,
    activo               BOOLEAN     NOT NULL DEFAULT TRUE,
    creado_en            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en       TIMESTAMPTZ,

    -- Correos siempre en minúsculas
    CHECK (correo_institucional = lower(correo_institucional)),
    CHECK (correo_personal IS NULL OR correo_personal = lower(correo_personal)),
    -- Nombre siempre en mayúsculas
    CHECK (nombre = upper(nombre))
);

CREATE INDEX IF NOT EXISTS idx_usuario_correo_institucional ON usuario (correo_institucional);
CREATE INDEX IF NOT EXISTS idx_usuario_creado_por           ON usuario (creado_por);
CREATE INDEX IF NOT EXISTS idx_usuario_tipo_documento       ON usuario (tipo_documento_id);


-- Sesiones activas. sesion.id (UUID v7) es el jti de ambos tokens.
-- refresh_token_hash : Argon2 del valor real del refresh token.
-- expira_en          : 1 día (refresh token TTL).
-- tipo_invalidacion_id + invalidado_en : se rellenan al revocar.
-- user_agent         : guardado para detección de anomalías.
CREATE TABLE IF NOT EXISTS sesion (
    id                   UUID        PRIMARY KEY,
    usuario_id           UUID        NOT NULL REFERENCES usuario(id) ON DELETE CASCADE,
    tipo_invalidacion_id UUID        REFERENCES tipo_invalidacion_sesion(id) ON DELETE RESTRICT,
    refresh_token_hash   TEXT        COLLATE "C" NOT NULL UNIQUE,
    ip_address           TEXT,
    user_agent           TEXT,
    activo               BOOLEAN     NOT NULL DEFAULT TRUE,
    expira_en            TIMESTAMPTZ NOT NULL,
    invalidado_en        TIMESTAMPTZ,
    creado_en            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en       TIMESTAMPTZ,

    -- Una sesión invalidada DEBE tener motivo y timestamp
    CHECK (
        (activo = TRUE  AND tipo_invalidacion_id IS NULL AND invalidado_en IS NULL) OR
        (activo = FALSE AND tipo_invalidacion_id IS NOT NULL AND invalidado_en IS NOT NULL)
    )
);

CREATE INDEX IF NOT EXISTS idx_sesion_usuario_id          ON sesion (usuario_id);
CREATE INDEX IF NOT EXISTS idx_sesion_refresh_token_hash  ON sesion (refresh_token_hash);
CREATE INDEX IF NOT EXISTS idx_sesion_activo_expira       ON sesion (activo, expira_en);
CREATE INDEX IF NOT EXISTS idx_sesion_tipo_invalidacion   ON sesion (tipo_invalidacion_id);


-- Log inmutable de eventos de sesión. Nunca se borra.
-- sesion_id → SET NULL si la sesión es eliminada; el historial persiste.
-- evento: login | logout | token_refresh | token_expired | revoked
CREATE TABLE IF NOT EXISTS sesion_historial (
    id          UUID        PRIMARY KEY,
    sesion_id   UUID        REFERENCES sesion(id) ON DELETE SET NULL,
    usuario_id  UUID        NOT NULL REFERENCES usuario(id) ON DELETE CASCADE,
    evento      TEXT        NOT NULL
                    CHECK (evento IN (
                        'login',
                        'logout',
                        'token_refresh',
                        'token_expired',
                        'revoked'
                    )),
    ip_address  TEXT,
    user_agent  TEXT,
    creado_en   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_sesion_historial_sesion_id  ON sesion_historial (sesion_id);
CREATE INDEX IF NOT EXISTS idx_sesion_historial_usuario_id ON sesion_historial (usuario_id);
CREATE INDEX IF NOT EXISTS idx_sesion_historial_creado_en  ON sesion_historial (creado_en);

-- ============================================================
-- ACCESS CONTROL
-- ============================================================

-- Perfiles del sistema.
-- ruta_dashboard : ruta exclusiva del perfil (ej: /dashboard/administrador).
--   Solo usuarios en usuario_perfil con ese perfil pueden acceder.
--   Si el usuario tiene un único perfil se redirige directo;
--   si tiene varios, la app muestra un selector.
CREATE TABLE IF NOT EXISTS perfil (
    id             UUID        PRIMARY KEY,
    nombre         TEXT        NOT NULL UNIQUE,
    descripcion    TEXT,
    ruta_dashboard TEXT        NOT NULL,
    creado_en      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ,
    creado_por     UUID        REFERENCES usuario(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_perfil_creado_por ON perfil (creado_por);


-- Roles granulares dentro de un perfil.
CREATE TABLE IF NOT EXISTS rol (
    id             UUID        PRIMARY KEY,
    perfil_id      UUID        NOT NULL REFERENCES perfil(id) ON DELETE CASCADE,
    nombre         TEXT        NOT NULL,
    descripcion    TEXT,
    creado_en      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ,
    creado_por     UUID        REFERENCES usuario(id) ON DELETE SET NULL,
    UNIQUE (perfil_id, nombre)
);

CREATE INDEX IF NOT EXISTS idx_rol_perfil_id  ON rol (perfil_id);
CREATE INDEX IF NOT EXISTS idx_rol_creado_por ON rol (creado_por);


-- Permisos atómicos del sistema. codigo usa COLLATE "C": recurso.accion.
CREATE TABLE IF NOT EXISTS permiso (
    id             UUID        PRIMARY KEY,
    codigo         TEXT        COLLATE "C" NOT NULL UNIQUE,
    nombre         TEXT        NOT NULL,
    descripcion    TEXT,
    creado_en      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ,
    creado_por     UUID        REFERENCES usuario(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_permiso_codigo     ON permiso (codigo);
CREATE INDEX IF NOT EXISTS idx_permiso_creado_por ON permiso (creado_por);


-- Permisos asignados a un rol.
CREATE TABLE IF NOT EXISTS rol_permiso (
    id             UUID        PRIMARY KEY,
    rol_id         UUID        NOT NULL REFERENCES rol(id) ON DELETE CASCADE,
    permiso_id     UUID        NOT NULL REFERENCES permiso(id) ON DELETE CASCADE,
    creado_en      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ,
    creado_por     UUID        REFERENCES usuario(id) ON DELETE SET NULL,
    UNIQUE (rol_id, permiso_id)
);

CREATE INDEX IF NOT EXISTS idx_rol_permiso_rol_id     ON rol_permiso (rol_id);
CREATE INDEX IF NOT EXISTS idx_rol_permiso_permiso_id ON rol_permiso (permiso_id);


-- Perfiles asignados a un usuario (pivote, muchos a muchos).
CREATE TABLE IF NOT EXISTS usuario_perfil (
    id             UUID        PRIMARY KEY,
    usuario_id     UUID        NOT NULL REFERENCES usuario(id) ON DELETE CASCADE,
    perfil_id      UUID        NOT NULL REFERENCES perfil(id) ON DELETE CASCADE,
    creado_en      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ,
    creado_por     UUID        REFERENCES usuario(id) ON DELETE SET NULL,
    UNIQUE (usuario_id, perfil_id)
);

CREATE INDEX IF NOT EXISTS idx_usuario_perfil_usuario_id ON usuario_perfil (usuario_id);
CREATE INDEX IF NOT EXISTS idx_usuario_perfil_perfil_id  ON usuario_perfil (perfil_id);


-- Roles asignados a un usuario.
CREATE TABLE IF NOT EXISTS usuario_rol (
    id             UUID        PRIMARY KEY,
    usuario_id     UUID        NOT NULL REFERENCES usuario(id) ON DELETE CASCADE,
    rol_id         UUID        NOT NULL REFERENCES rol(id) ON DELETE CASCADE,
    creado_en      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ,
    creado_por     UUID        REFERENCES usuario(id) ON DELETE SET NULL,
    UNIQUE (usuario_id, rol_id)
);

CREATE INDEX IF NOT EXISTS idx_usuario_rol_usuario_id ON usuario_rol (usuario_id);
CREATE INDEX IF NOT EXISTS idx_usuario_rol_rol_id     ON usuario_rol (rol_id);

-- ============================================================
-- INSTITUTIONAL STRUCTURE
-- ============================================================

-- Regionales del SENA. Nivel más alto de la jerarquía institucional.
CREATE TABLE IF NOT EXISTS regional (
    id             UUID        PRIMARY KEY,
    nombre         TEXT        NOT NULL UNIQUE,
    creado_en      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ,
    creado_por     UUID        REFERENCES usuario(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_regional_creado_por ON regional (creado_por);


-- Centros de formación. No se elimina una regional con centros (RESTRICT).
CREATE TABLE IF NOT EXISTS centro (
    id             UUID        PRIMARY KEY,
    regional_id    UUID        NOT NULL REFERENCES regional(id) ON DELETE RESTRICT,
    nombre         TEXT        NOT NULL,
    creado_en      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ,
    creado_por     UUID        REFERENCES usuario(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_centro_regional_id ON centro (regional_id);
CREATE INDEX IF NOT EXISTS idx_centro_creado_por  ON centro (creado_por);


-- Coordinaciones académicas dentro de un centro.
CREATE TABLE IF NOT EXISTS coordinacion (
    id             UUID        PRIMARY KEY,
    centro_id      UUID        NOT NULL REFERENCES centro(id) ON DELETE RESTRICT,
    nombre         TEXT        NOT NULL,
    creado_en      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ,
    creado_por     UUID        REFERENCES usuario(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_coordinacion_centro_id  ON coordinacion (centro_id);
CREATE INDEX IF NOT EXISTS idx_coordinacion_creado_por ON coordinacion (creado_por);


-- Sedes físicas dentro de un centro.
CREATE TABLE IF NOT EXISTS sede (
    id             UUID        PRIMARY KEY,
    centro_id      UUID        NOT NULL REFERENCES centro(id) ON DELETE RESTRICT,
    nombre         TEXT        NOT NULL,
    creado_en      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ,
    creado_por     UUID        REFERENCES usuario(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_sede_centro_id  ON sede (centro_id);
CREATE INDEX IF NOT EXISTS idx_sede_creado_por ON sede (creado_por);


-- Ambientes o aulas dentro de una sede.
CREATE TABLE IF NOT EXISTS ambiente (
    id             UUID        PRIMARY KEY,
    sede_id        UUID        NOT NULL REFERENCES sede(id) ON DELETE RESTRICT,
    nombre         TEXT        NOT NULL,
    capacidad      INTEGER,
    creado_en      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ,
    creado_por     UUID        REFERENCES usuario(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_ambiente_sede_id    ON ambiente (sede_id);
CREATE INDEX IF NOT EXISTS idx_ambiente_creado_por ON ambiente (creado_por);

-- ============================================================
-- ACADEMIC KNOWLEDGE STRUCTURE
-- ============================================================

-- Redes de conocimiento del SENA (ej: Tecnología, Agroindustria).
CREATE TABLE IF NOT EXISTS red_conocimiento (
    id             UUID        PRIMARY KEY,
    nombre         TEXT        NOT NULL UNIQUE,
    creado_en      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ,
    creado_por     UUID        REFERENCES usuario(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_red_conocimiento_creado_por ON red_conocimiento (creado_por);


-- Áreas de desempeño dentro de una red de conocimiento.
CREATE TABLE IF NOT EXISTS area (
    id                   UUID        PRIMARY KEY,
    red_conocimiento_id  UUID        NOT NULL REFERENCES red_conocimiento(id) ON DELETE RESTRICT,
    nombre               TEXT        NOT NULL,
    creado_en            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en       TIMESTAMPTZ,
    creado_por           UUID        REFERENCES usuario(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_area_red_conocimiento_id ON area (red_conocimiento_id);
CREATE INDEX IF NOT EXISTS idx_area_creado_por          ON area (creado_por);


-- Niveles de formación (Técnico, Tecnólogo, Operario, etc.).
CREATE TABLE IF NOT EXISTS nivel_formacion (
    id             UUID        PRIMARY KEY,
    nombre         TEXT        NOT NULL UNIQUE,
    creado_en      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ,
    creado_por     UUID        REFERENCES usuario(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_nivel_formacion_creado_por ON nivel_formacion (creado_por);

-- ============================================================
-- PEOPLE
-- ============================================================

-- nombres y apellidos siempre en MAYÚSCULAS (CHECK).
-- documento usa COLLATE "C": número de identificación alphanumeric.

-- Instructores vinculados a un centro y opcionalmente a un área.
CREATE TABLE IF NOT EXISTS instructor (
    id             UUID        PRIMARY KEY,
    centro_id      UUID        NOT NULL REFERENCES centro(id) ON DELETE RESTRICT,
    area_id        UUID        REFERENCES area(id) ON DELETE SET NULL,
    usuario_id     UUID        REFERENCES usuario(id) ON DELETE SET NULL,
    tipo_doc_id    UUID        REFERENCES tipo_documento(id) ON DELETE RESTRICT,
    documento      TEXT        COLLATE "C" NOT NULL,
    nombres        TEXT        NOT NULL,
    apellidos      TEXT        NOT NULL,
    correo         TEXT,
    genero         TEXT        NOT NULL DEFAULT 'M',
    creado_en      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ,
    creado_por     UUID        REFERENCES usuario(id) ON DELETE SET NULL,

    CHECK (nombres   = upper(nombres)),
    CHECK (apellidos = upper(apellidos))
);

CREATE INDEX IF NOT EXISTS idx_instructor_centro_id  ON instructor (centro_id);
CREATE INDEX IF NOT EXISTS idx_instructor_area_id    ON instructor (area_id);
CREATE INDEX IF NOT EXISTS idx_instructor_usuario_id ON instructor (usuario_id);
CREATE INDEX IF NOT EXISTS idx_instructor_creado_por ON instructor (creado_por);


-- Aprendices vinculados a una regional.
CREATE TABLE IF NOT EXISTS aprendiz (
    id             UUID        PRIMARY KEY,
    regional_id    UUID        NOT NULL REFERENCES regional(id) ON DELETE RESTRICT,
    usuario_id     UUID        REFERENCES usuario(id) ON DELETE SET NULL,
    tipo_doc_id    UUID        REFERENCES tipo_documento(id) ON DELETE RESTRICT,
    documento      TEXT        COLLATE "C" NOT NULL,
    nombres        TEXT        NOT NULL,
    apellidos      TEXT        NOT NULL,
    correo         TEXT,
    ficha          TEXT,
    creado_en      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ,
    creado_por     UUID        REFERENCES usuario(id) ON DELETE SET NULL,

    CHECK (nombres   = upper(nombres)),
    CHECK (apellidos = upper(apellidos))
);

CREATE INDEX IF NOT EXISTS idx_aprendiz_regional_id ON aprendiz (regional_id);
CREATE INDEX IF NOT EXISTS idx_aprendiz_usuario_id  ON aprendiz (usuario_id);
CREATE INDEX IF NOT EXISTS idx_aprendiz_creado_por  ON aprendiz (creado_por);


-- Personal administrativo vinculado a un centro.
CREATE TABLE IF NOT EXISTS personal_administrativo (
    id             UUID        PRIMARY KEY,
    centro_id      UUID        NOT NULL REFERENCES centro(id) ON DELETE RESTRICT,
    usuario_id     UUID        REFERENCES usuario(id) ON DELETE SET NULL,
    tipo_doc_id    UUID        REFERENCES tipo_documento(id) ON DELETE RESTRICT,
    documento      TEXT        COLLATE "C" NOT NULL,
    nombres        TEXT        NOT NULL,
    apellidos      TEXT        NOT NULL,
    correo         TEXT,
    cargo          TEXT        NOT NULL,
    creado_en      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ,
    creado_por     UUID        REFERENCES usuario(id) ON DELETE SET NULL,

    CHECK (nombres   = upper(nombres)),
    CHECK (apellidos = upper(apellidos))
);

CREATE INDEX IF NOT EXISTS idx_personal_administrativo_centro_id  ON personal_administrativo (centro_id);
CREATE INDEX IF NOT EXISTS idx_personal_administrativo_usuario_id ON personal_administrativo (usuario_id);
CREATE INDEX IF NOT EXISTS idx_personal_administrativo_creado_por ON personal_administrativo (creado_por);

-- ============================================================
-- ACADEMIC CONTENT CHAIN
-- ============================================================

-- Proyecto formativo: documento guía del proceso de formación.
CREATE TABLE IF NOT EXISTS proyecto_formativo (
    id             UUID        PRIMARY KEY,
    codigo         TEXT        COLLATE "C" NOT NULL UNIQUE,
    nombre         TEXT        NOT NULL,
    creado_en      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ,
    creado_por     UUID        REFERENCES usuario(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_proyecto_formativo_creado_por ON proyecto_formativo (creado_por);


-- Fases del proyecto formativo (ej: Análisis, Planeación, Ejecución).
CREATE TABLE IF NOT EXISTS fase_proyecto (
    id                    UUID        PRIMARY KEY,
    proyecto_formativo_id UUID        NOT NULL REFERENCES proyecto_formativo(id) ON DELETE CASCADE,
    nombre                TEXT        NOT NULL,
    creado_en             TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en        TIMESTAMPTZ,
    creado_por            UUID        REFERENCES usuario(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_fase_proyecto_proyecto_formativo_id ON fase_proyecto (proyecto_formativo_id);
CREATE INDEX IF NOT EXISTS idx_fase_proyecto_creado_por            ON fase_proyecto (creado_por);


-- Actividades del proyecto agrupadas por fase.
CREATE TABLE IF NOT EXISTS actividad_proyecto (
    id               UUID        PRIMARY KEY,
    fase_proyecto_id UUID        NOT NULL REFERENCES fase_proyecto(id) ON DELETE CASCADE,
    nombre           TEXT        NOT NULL,
    creado_en        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en   TIMESTAMPTZ,
    creado_por       UUID        REFERENCES usuario(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_actividad_proyecto_fase_proyecto_id ON actividad_proyecto (fase_proyecto_id);
CREATE INDEX IF NOT EXISTS idx_actividad_proyecto_creado_por       ON actividad_proyecto (creado_por);


-- Actividades de aprendizaje dentro de una actividad de proyecto.
CREATE TABLE IF NOT EXISTS actividad_aprendizaje (
    id                    UUID        PRIMARY KEY,
    actividad_proyecto_id UUID        NOT NULL REFERENCES actividad_proyecto(id) ON DELETE CASCADE,
    nombre                TEXT        NOT NULL,
    descripcion           TEXT,
    fecha_inicio          DATE,
    fecha_fin             DATE,
    orden                 INTEGER     NOT NULL DEFAULT 0,
    creado_en             TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en        TIMESTAMPTZ,
    creado_por            UUID        REFERENCES usuario(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_actividad_aprendizaje_actividad_proyecto_id ON actividad_aprendizaje (actividad_proyecto_id);
CREATE INDEX IF NOT EXISTS idx_actividad_aprendizaje_creado_por            ON actividad_aprendizaje (creado_por);


-- Guía de aprendizaje adjunta a una actividad (1:1).
CREATE TABLE IF NOT EXISTS guia_aprendizaje (
    id                       UUID        PRIMARY KEY,
    actividad_aprendizaje_id UUID        NOT NULL UNIQUE
                                 REFERENCES actividad_aprendizaje(id) ON DELETE CASCADE,
    url                      TEXT        NOT NULL,
    subido_en                TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    creado_en                TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en           TIMESTAMPTZ,
    creado_por               UUID        REFERENCES usuario(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_guia_aprendizaje_actividad_aprendizaje_id ON guia_aprendizaje (actividad_aprendizaje_id);
CREATE INDEX IF NOT EXISTS idx_guia_aprendizaje_creado_por               ON guia_aprendizaje (creado_por);


-- Evidencia de aprendizaje asociada a una actividad (1:1).
CREATE TABLE IF NOT EXISTS evidencia_aprendizaje (
    id                       UUID        PRIMARY KEY,
    actividad_aprendizaje_id UUID        NOT NULL UNIQUE
                                 REFERENCES actividad_aprendizaje(id) ON DELETE CASCADE,
    descripcion              TEXT,
    creado_en                TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en           TIMESTAMPTZ,
    creado_por               UUID        REFERENCES usuario(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_evidencia_aprendizaje_actividad_aprendizaje_id ON evidencia_aprendizaje (actividad_aprendizaje_id);
CREATE INDEX IF NOT EXISTS idx_evidencia_aprendizaje_creado_por               ON evidencia_aprendizaje (creado_por);


-- Entrega de evidencia por un aprendiz, con calificación del instructor.
-- usuario_id (aprendiz) : ON DELETE RESTRICT — no se borra un usuario con entregas.
CREATE TABLE IF NOT EXISTS entrega_evidencia (
    id                       UUID        PRIMARY KEY,
    evidencia_aprendizaje_id UUID        NOT NULL
                                 REFERENCES evidencia_aprendizaje(id) ON DELETE CASCADE,
    usuario_id               UUID        NOT NULL REFERENCES usuario(id) ON DELETE RESTRICT,
    url                      TEXT,
    calificacion             NUMERIC(5,2),
    observaciones            TEXT,
    retroalimentacion        TEXT,
    aprueba                  BOOLEAN,
    calificado_en            TIMESTAMPTZ,
    entregado_en             TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    creado_en                TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en           TIMESTAMPTZ,
    creado_por               UUID        REFERENCES usuario(id) ON DELETE SET NULL,
    UNIQUE (evidencia_aprendizaje_id, usuario_id)
);

CREATE INDEX IF NOT EXISTS idx_entrega_evidencia_evidencia_aprendizaje_id ON entrega_evidencia (evidencia_aprendizaje_id);
CREATE INDEX IF NOT EXISTS idx_entrega_evidencia_usuario_id               ON entrega_evidencia (usuario_id);
CREATE INDEX IF NOT EXISTS idx_entrega_evidencia_creado_por               ON entrega_evidencia (creado_por);


-- Secciones dentro de una actividad de aprendizaje.
CREATE TABLE IF NOT EXISTS seccion_actividad (
    id                       UUID        PRIMARY KEY,
    actividad_aprendizaje_id UUID        NOT NULL
                                 REFERENCES actividad_aprendizaje(id) ON DELETE CASCADE,
    nombre                   TEXT        NOT NULL,
    descripcion              TEXT,
    archivo_url              TEXT,
    archivo_tipo             TEXT,
    fecha_inicio             DATE,
    fecha_fin                DATE,
    orden                    INTEGER     NOT NULL DEFAULT 0,
    creado_en                TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en           TIMESTAMPTZ,
    creado_por               UUID        REFERENCES usuario(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_seccion_actividad_actividad_aprendizaje_id ON seccion_actividad (actividad_aprendizaje_id);
CREATE INDEX IF NOT EXISTS idx_seccion_actividad_creado_por               ON seccion_actividad (creado_por);


-- Subsecciones dentro de una sección de actividad.
CREATE TABLE IF NOT EXISTS sub_seccion_actividad (
    id             UUID        PRIMARY KEY,
    seccion_id     UUID        NOT NULL REFERENCES seccion_actividad(id) ON DELETE CASCADE,
    nombre         TEXT        NOT NULL,
    descripcion    TEXT,
    archivo_url    TEXT,
    archivo_tipo   TEXT,
    fecha_inicio   DATE,
    fecha_fin      DATE,
    orden          INTEGER     NOT NULL DEFAULT 0,
    creado_en      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ,
    creado_por     UUID        REFERENCES usuario(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_sub_seccion_actividad_seccion_id ON sub_seccion_actividad (seccion_id);
CREATE INDEX IF NOT EXISTS idx_sub_seccion_actividad_creado_por ON sub_seccion_actividad (creado_por);


-- Guías adjuntas a una actividad de proyecto (uso del instructor).
CREATE TABLE IF NOT EXISTS guia_actividad_proyecto (
    id                    UUID        PRIMARY KEY,
    actividad_proyecto_id UUID        NOT NULL
                              REFERENCES actividad_proyecto(id) ON DELETE CASCADE,
    nombre                TEXT,
    descripcion           TEXT,
    url                   TEXT        NOT NULL,
    orden                 INTEGER     NOT NULL DEFAULT 0,
    subido_en             TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    creado_en             TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en        TIMESTAMPTZ,
    creado_por            UUID        REFERENCES usuario(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_guia_actividad_proyecto_actividad_proyecto_id ON guia_actividad_proyecto (actividad_proyecto_id);
CREATE INDEX IF NOT EXISTS idx_guia_actividad_proyecto_creado_por            ON guia_actividad_proyecto (creado_por);

-- ============================================================
-- PROGRAMS & FICHAS
-- ============================================================

-- Programa de formación: combinación de área y nivel.
CREATE TABLE IF NOT EXISTS programa_formacion (
    id                  UUID        PRIMARY KEY,
    area_id             UUID        NOT NULL REFERENCES area(id) ON DELETE RESTRICT,
    nivel_formacion_id  UUID        NOT NULL REFERENCES nivel_formacion(id) ON DELETE RESTRICT,
    nombre              TEXT        NOT NULL,
    creado_en           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en      TIMESTAMPTZ,
    creado_por          UUID        REFERENCES usuario(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_programa_formacion_area_id            ON programa_formacion (area_id);
CREATE INDEX IF NOT EXISTS idx_programa_formacion_nivel_formacion_id ON programa_formacion (nivel_formacion_id);
CREATE INDEX IF NOT EXISTS idx_programa_formacion_creado_por         ON programa_formacion (creado_por);


-- Ficha de formación: cohorte de aprendices en un programa.
CREATE TABLE IF NOT EXISTS ficha_formacion (
    id                    UUID        PRIMARY KEY,
    numero                TEXT        COLLATE "C" NOT NULL UNIQUE,
    programa_formacion_id UUID        NOT NULL REFERENCES programa_formacion(id) ON DELETE RESTRICT,
    proyecto_formativo_id UUID        REFERENCES proyecto_formativo(id) ON DELETE SET NULL,
    coordinacion_id       UUID        NOT NULL REFERENCES coordinacion(id) ON DELETE RESTRICT,
    instructor_id         UUID        REFERENCES instructor(id) ON DELETE SET NULL,
    creado_en             TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en        TIMESTAMPTZ,
    creado_por            UUID        REFERENCES usuario(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_ficha_formacion_programa_formacion_id ON ficha_formacion (programa_formacion_id);
CREATE INDEX IF NOT EXISTS idx_ficha_formacion_proyecto_formativo_id ON ficha_formacion (proyecto_formativo_id);
CREATE INDEX IF NOT EXISTS idx_ficha_formacion_coordinacion_id       ON ficha_formacion (coordinacion_id);
CREATE INDEX IF NOT EXISTS idx_ficha_formacion_instructor_id         ON ficha_formacion (instructor_id);
CREATE INDEX IF NOT EXISTS idx_ficha_formacion_creado_por            ON ficha_formacion (creado_por);


-- Competencias asignadas: instructores que dictan una ficha.
CREATE TABLE IF NOT EXISTS ficha_instructor_competencia (
    id             UUID        PRIMARY KEY,
    ficha_id       UUID        NOT NULL REFERENCES ficha_formacion(id) ON DELETE CASCADE,
    instructor_id  UUID        NOT NULL REFERENCES instructor(id) ON DELETE CASCADE,
    creado_en      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ,
    creado_por     UUID        REFERENCES usuario(id) ON DELETE SET NULL,
    UNIQUE (ficha_id, instructor_id)
);

CREATE INDEX IF NOT EXISTS idx_ficha_instructor_competencia_ficha_id      ON ficha_instructor_competencia (ficha_id);
CREATE INDEX IF NOT EXISTS idx_ficha_instructor_competencia_instructor_id ON ficha_instructor_competencia (instructor_id);
CREATE INDEX IF NOT EXISTS idx_ficha_instructor_competencia_creado_por    ON ficha_instructor_competencia (creado_por);


-- Asistencia de aprendices por ficha y fecha.
CREATE TABLE IF NOT EXISTS asistencia_aprendiz (
    id             UUID        PRIMARY KEY,
    ficha_id       UUID        NOT NULL REFERENCES ficha_formacion(id) ON DELETE CASCADE,
    aprendiz_id    UUID        NOT NULL REFERENCES aprendiz(id) ON DELETE CASCADE,
    fecha          DATE        NOT NULL,
    estado         TEXT        NOT NULL DEFAULT 'Presente',
    creado_en      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ,
    creado_por     UUID        REFERENCES usuario(id) ON DELETE SET NULL,
    UNIQUE (ficha_id, aprendiz_id, fecha)
);

CREATE INDEX IF NOT EXISTS idx_asistencia_aprendiz_ficha_id    ON asistencia_aprendiz (ficha_id);
CREATE INDEX IF NOT EXISTS idx_asistencia_aprendiz_aprendiz_id ON asistencia_aprendiz (aprendiz_id);
CREATE INDEX IF NOT EXISTS idx_asistencia_aprendiz_creado_por  ON asistencia_aprendiz (creado_por);

-- ============================================================
-- LEARNER-FACING EXTRAS
-- ============================================================

-- Fases del proceso formativo SENA (catálogo independiente).
CREATE TABLE IF NOT EXISTS fase (
    id             UUID         PRIMARY KEY,
    nombre         VARCHAR(150) NOT NULL UNIQUE,
    orden          SMALLINT     NOT NULL DEFAULT 1,
    descripcion    TEXT,
    creado_en      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ
);


-- Notificaciones para cualquier usuario del sistema.
CREATE TABLE IF NOT EXISTS notificacion (
    id             UUID        PRIMARY KEY,
    usuario_id     UUID        NOT NULL REFERENCES usuario(id) ON DELETE CASCADE,
    mensaje        TEXT        NOT NULL,
    tipo           VARCHAR(10) NOT NULL DEFAULT 'info'
                       CHECK (tipo IN ('info', 'success', 'warning', 'danger')),
    leida          BOOLEAN     NOT NULL DEFAULT FALSE,
    url_destino    TEXT,
    creado_en      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ,
    creado_por     UUID        REFERENCES usuario(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_notificacion_usuario_id ON notificacion (usuario_id);
CREATE INDEX IF NOT EXISTS idx_notificacion_creado_por ON notificacion (creado_por);

COMMIT;
